### ISSUE TITLE
Cannot find module '../../object/valid-value' on npm install

### ISSUE THREAD

**Issue by zanona** [imagemin/imagemin#104]
I am not sure what is really happening but it usually to install fine from my CI environment, however now `npm install` is returning the following chain of errors. Any ideas?

```sh
> gifsicle@3.0.0 postinstall /home/ubuntu/indigofx.co.uk/node_modules/pakku/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle
> node lib/install.js

module.js:333
    throw err;
          ^
Error: Cannot find module '../../object/valid-value'
    at Function.Module._resolveFilename (module.js:331:15)
    at Function.Module._load (module.js:273:25)
    at Module.require (module.js:357:17)
    at require (module.js:373:17)
    at Object.<anonymous> (/home/ubuntu/indigofx.co.uk/node_modules/pakku/node_modules/imagemin/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/unique-stream/node_modules/es6-set/node_modules/es5-ext/array/#/clear.js:7:13)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:349:32)
    at Function.Module._load (module.js:305:12)
    at Module.require (module.js:357:17)
    at require (module.js:373:17)
    at Object.<anonymous> (/home/ubuntu/indigofx.co.uk/node_modules/pakku/node_modules/imagemin/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/unique-stream/node_modules/es6-set/polyfill.js:3:22)

> jpegtran-bin@3.0.1 postinstall /home/ubuntu/indigofx.co.uk/node_modules/pakku/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin
> node lib/install.js

module.js:333
    throw err;
          ^
Error: Cannot find module '../../object/valid-value'
    at Function.Module._resolveFilename (module.js:331:15)
    at Function.Module._load (module.js:273:25)
    at Module.require (module.js:357:17)
    at require (module.js:373:17)
    at Object.<anonymous> (/home/ubuntu/indigofx.co.uk/node_modules/pakku/node_modules/imagemin/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/unique-stream/node_modules/es6-set/node_modules/es5-ext/array/#/clear.js:7:13)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:349:32)
    at Function.Module._load (module.js:305:12)
    at Module.require (module.js:357:17)
npm WARN optional dep failed, continuing imagemin-gifsicle@4.2.0

> optipng-bin@3.0.2 postinstall /home/ubuntu/indigofx.co.uk/node_modules/pakku/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin
> node lib/install.js

module.js:333
    throw err;
          ^
Error: Cannot find module '../../object/valid-value'
    at Function.Module._resolveFilename (module.js:331:15)
    at Function.Module._load (module.js:273:25)
    at Module.require (module.js:357:17)
    at require (module.js:373:17)
    at Object.<anonymous> (/home/ubuntu/indigofx.co.uk/node_modules/pakku/node_modules/imagemin/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/unique-stream/node_modules/es6-set/node_modules/es5-ext/array/#/clear.js:7:13)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:349:32)
    at Function.Module._load (module.js:305:12)
    at Module.require (module.js:357:17)
    at require (module.js:373:17)
    at Object.<anonymous> (/home/ubuntu/indigofx.co.uk/node_modules/pakku/node_modules/imagemin/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/unique-stream/node_modules/es6-set/polyfill.js:3:22)
npm WARN optional dep failed, continuing imagemin-jpegtran@4.2.0
npm WARN optional dep failed, continuing imagemin-optipng@4.3.0
```

**Comment by shinnn** [comment]
> at Object.<anonymous> (/home/ubuntu/indigofx.co.uk/node_modules/pakku/node_modules/imagemin/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/unique-stream/node_modules/es6-set/node_modules/es5-ext/array/#/clear.js:7:13)

The root cause is this line: https://github.com/medikoo/es5-ext/blob/83b2182f67b1d213e4336772ed6b04f66f5e3550/array/%23/clear.js

**Comment by zanona** [comment]
Thanks for the information @shinnn. 
Do you think that by updating image-min would solve the issue?
I can see it happens on vinyl-fs dependency, which I recall to have been removed?

Thanks again.

**Comment by shinnn** [comment]
> Do you think that by updating image-min would solve the issue?

I don't know, because I've never run into the same problem once.

> I can see it happens on vinyl-fs dependency, which I recall to have been removed?

imagemin v3 still uses vinyl.

============

Please report it on the correct repo if the problem still occurs on every installation.

**Comment by gmetais** [comment]
I had the same problem on Travis CI.
Updating nodejs to v0.12.4 fixed the problem for me.

**Comment by shinnn** [comment]
Note that I submitted [a PR](https://github.com/eugeneware/unique-stream/pull/10) to [unique-stream](https://github.com/eugeneware/unique-stream) to drop es6-set dependency. It would totally fix this problem because currently vinyl-fs depends on unique-stream.
