### ISSUE TITLE
imagemin not working anymore on Debian?

### ISSUE THREAD

**Issue by thibaultlavoisey** [imagemin/imagemin#105]
Hello,

I use imagemin via Gulp on Debian. From 2 days now, imagemin not working anymore.

On install:

```
> spawn-sync@1.0.11 postinstall /home/www/example.com/releases/20150608214507/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/node_modules/bin-wrapper/node_modules/bin-check/node_modules/spawn-sync
> node postinstall


> spawn-sync@1.0.11 postinstall /home/www/example.com/releases/20150608214507/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-wrapper/node_modules/bin-check/node_modules/spawn-sync
> node postinstall


> spawn-sync@1.0.11 postinstall /home/www/example.com/releases/20150608214507/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-wrapper/node_modules/bin-check/node_modules/spawn-sync
> node postinstall

-
> jpegtran-bin@3.0.1 postinstall /home/www/example.com/releases/20150608214507/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin
> node lib/install.js

  ⚠ The `/home/www/example.com/releases/20150608214507/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/vendor/jpegtran` binary doesn't seem to work correctly
  ⚠ jpegtran pre-build test failed
  ℹ compiling from source
  ✖ Error: ./configure --disable-shared --prefix="/home/www/example.com/releases/20150608214507/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/vendor" --bindir="/home/www/example.com/releases/20150608214507/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/vendor" && make install
Command failed: /bin/sh -c ./configure --disable-shared --prefix="/home/www/example.com/releases/20150608214507/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/vendor" --bindir="/home/www/example.com/releases/20150608214507/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/vendor"
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details.

    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
        .pipe(gulp.dest('public/img'));
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

> gifsicle@3.0.0 postinstall /home/www/example.com/releases/20150608214507/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle
> node lib/install.js

  ⚠ The `/home/www/example.com/releases/20150608214507/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/vendor/gifsicle` binary doesn't seem to work correctly
  ⚠ gifsicle pre-build test failed
  ℹ compiling from source
  ✖ Error: autoreconf -ivf && ./configure --disable-gifview --disable-gifdiff --prefix="/home/www/example.com/releases/20150608214507/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/vendor" --bindir="/home/www/example.com/releases/20150608214507/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/vendor" && make install
Command failed: /bin/sh -c autoreconf -ivf
/bin/sh: autoreconf: command not found

    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)

> optipng-bin@3.0.2 postinstall /home/www/example.com/releases/20150608214507/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin
> node lib/install.js

  ✔ optipng pre-build test passed successfully
gulp-imagemin@2.2.1 node_modules/gulp-imagemin
├── object-assign@2.1.1
├── chalk@1.0.0 (escape-string-regexp@1.0.3, ansi-styles@2.0.1, supports-color@1.3.1, has-ansi@1.0.3, strip-ansi@2.0.1)
├── through2-concurrent@0.3.1 (through2@0.6.5)
├── pretty-bytes@1.0.4 (get-stdin@4.0.1, meow@3.1.0)
├── gulp-util@3.0.5 (array-differ@1.0.0, array-uniq@1.0.2, lodash._reescape@3.0.0, lodash._reinterpolate@3.0.0, lodash._reevaluate@3.0.0, beeper@1.1.0, replace-ext@0.0.1, minimist@1.1.1, vinyl@0.4.6, lodash.template@3.6.1, through2@0.6.5, dateformat@1.0.11, multipipe@0.1.2)
└── imagemin@3.2.0 (get-stdin@4.0.1, path-exists@1.0.0, optional@0.1.3, buffer-to-vinyl@1.0.0, through2@0.6.5, meow@3.1.0, concat-stream@1.4.8, stream-combiner2@1.0.2, imagemin-svgo@4.1.2, vinyl-fs@1.0.0, imagemin-jpegtran@4.2.0, imagemin-gifsicle@4.2.0, imagemin-optipng@4.3.0)
```

On build:

```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: write EPIPE
    at exports._errnoException (util.js:746:11)
    at WriteWrap.afterWrite (net.js:775:14)
```

Imagemin worked fine 2/3 days ago.

It also works fine on Mac OS X. The problem is only on the Debian server. I tried to delete and reinstall packages, not better.

I use imagemin to optimize images of many Websites before deploy to production server so I disable the imagemin gulp task for now.

Let me know if I can help.

Bye,

**Comment by JimiC** [comment]
I had a similar issue on Windows 10 with VS 2015. In my case the problem was that the `vendor` folder was not being created. As soon as I copied it in, things worked.

**Comment by kevva** [comment]
@thibaultlavoisey, you need to install the `build-essential` package, and maybe `nasm` too if the compilation fails.

**Comment by ezraroi** [comment]
Also SLES11 machines are not working anymore and also Windows

**Comment by ezraroi** [comment]
any updates on this? currently we can not use grunt-contrib-imagemin anymore

**Comment by shinnn** [comment]
@ezraroi Just saying "not working" is exactly the same as saying nothing. http://www.catb.org/esr/faqs/smart-questions.html

We'd be very happy if could tell us your Node version, npm version, OS version, each module version,  error log and a URL of the small repository that can reproduce the error. A good pull request to solve the problem is much more welcome.

**Comment by ezraroi** [comment]
@shinnn Sure, will do so

**Comment by thibaultlavoisey** [comment]
@kevva Looks good! I installed both and it's ok. Maybe add this info in a troubleshooting page? Thank's
