### ISSUE TITLE
Image-min no longer working - OSX

### ISSUE THREAD

**Issue by shaneparsons** [imagemin/imagemin#109]
Very similar to #105, image-min doesn't seem to be working for me anymore.

I'm using it through gulp in OSX, and it always throws the following error at me:

    events.js:85
        throw er; // Unhandled 'error' event
                ^
    Error: spawn /Applications/MAMP/htdocs/projectname/node_modules/imagemin-pngquant/node_modules/pngquant-bin/vendor/pngquant ENOENT
        at exports._errnoException (util.js:746:11)
        at Process.ChildProcess._handle.onexit (child_process.js:1046:32)
        at child_process.js:1137:20
        at process._tickCallback (node.js:355:11)

I've tried updating and re-installing **gulp-image-min** and **imagemin-pngquant** with no success.

Thanks

**Comment by shinnn** [comment]
I'm currently using OS X 10.10.3 and has no trouble.

@shaneparsons 

1. Can you show us all the logs of the installation error?
2. Can you show us the result of:

    ```
    npm ls gulp-imagemin imagemin pngquant
    ```

**Comment by shaneparsons** [comment]
1. Sorry about the confusion, I **was** successfully able to install image-min and pngquant, the "with no success" meant it did not fix my error.
On that note, I do not have a *npm-debug.log* file.

2. running `npm ls gulp-imagemin imagemin pngquant` output this:
```
memoriesmyway@1.0.0 /Applications/MAMP/htdocs/memoriesmyway
└─┬ gulp-imagemin@2.2.1 
  └── imagemin@3.2.0
```

however, I assume you were looking for the input of `npm ls gulp-imagemin imagemin-pngquant`, which is:
```
projectname@1.0.0 /Applications/MAMP/htdocs/projectname
├── gulp-imagemin@2.2.1 
└── imagemin-pngquant@4.1.0 
```

**Comment by kevva** [comment]
You should've seen some messages when installing though if anything went wrong.

**Comment by shaneparsons** [comment]
This is the only thing that seems relevent:
```
> spawn-sync@1.0.11 postinstall /Applications/MAMP/htdocs/memoriesmyway/node_modules/imagemin-pngquant/node_modules/pngquant-bin/node_modules/bin-wrapper/node_modules/bin-check/node_modules/spawn-sync
> node postinstall

\
> pngquant-bin@3.0.0 postinstall /Applications/MAMP/htdocs/memoriesmyway/node_modules/imagemin-pngquant/node_modules/pngquant-bin
> node lib/install.js

module.js:338
    throw err;
          ^
Error: Cannot find module 'gulp-util'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Applications/MAMP/htdocs/memoriesmyway/node_modules/imagemin-pngquant/node_modules/pngquant-bin/node_modules/bin-wrapper/node_modules/download/node_modules/gulp-decompress/index.js:5:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! path /Applications/MAMP/htdocs/memoriesmyway/node_modules/gulp-uglify/node_modules/.bin/uglifyjs
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, unlink '/Applications/MAMP/htdocs/memoriesmyway/node_modules/gulp-uglify/node_modules/.bin/uglifyjs'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, unlink '/Applications/MAMP/htdocs/memoriesmyway/node_modules/gulp-uglify/node_modules/.bin/uglifyjs']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/Applications/MAMP/htdocs/memoriesmyway/node_modules/gulp-uglify/node_modules/.bin/uglifyjs' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
npm ERR! error rolling back Error: EACCES, unlink '/Applications/MAMP/htdocs/memoriesmyway/node_modules/gulp-uglify/node_modules/.bin/uglifyjs'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: EACCES, unlink '/Applications/MAMP/htdocs/memoriesmyway/node_modules/gulp-uglify/node_modules/.bin/uglifyjs']
npm ERR! error rolling back   errno: -13,
npm ERR! error rolling back   code: 'EACCES',
npm ERR! error rolling back   path: '/Applications/MAMP/htdocs/memoriesmyway/node_modules/gulp-uglify/node_modules/.bin/uglifyjs' }

npm ERR! Please include the following file with any support request:
npm ERR!     /Applications/MAMP/htdocs/memoriesmyway/npm-debug.log
```
However when I ran it with sudo afterwards everything went fine

**Comment by shaneparsons** [comment]
I didn't mention everything worked fine until a few days ago when it just stopped working.. no changes were made to the gulpfile prior.

**Comment by kevva** [comment]
Well, don't use `sudo`, set the correct permissions instead. And when you ran it afterwards you did see `pre-build ran successfully` or likewise?

**Comment by shinnn** [comment]
After you fix permissions I recommend upgrading `npm` command to the latest version.

```
npn install --global npm
```

**Comment by shaneparsons** [comment]
Here's the relevent feedback from the sudo install:

``` 
> jpegtran-bin@3.0.1 postinstall /Applications/MAMP/htdocs/memoriesmyway/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin
> node lib/install.js

  ✔ jpegtran pre-build test passed successfully

> optipng-bin@3.0.2 postinstall /Applications/MAMP/htdocs/memoriesmyway/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin
> node lib/install.js

  ✔ optipng pre-build test passed successfully

> gifsicle@3.0.0 postinstall /Applications/MAMP/htdocs/memoriesmyway/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle
> node lib/install.js

  ✔ gifsicle pre-build test passed successfully
```
```
gulp-imagemin@2.2.1 node_modules/gulp-imagemin
├── object-assign@2.1.1
├── chalk@1.0.0 (ansi-styles@2.0.1, escape-string-regexp@1.0.3, supports-color@1.3.1, has-ansi@1.0.3, strip-ansi@2.0.1)
├── through2-concurrent@0.3.1 (through2@0.6.5)
├── pretty-bytes@1.0.4 (get-stdin@4.0.1, meow@3.1.0)
└── imagemin@3.2.0 (get-stdin@4.0.1, path-exists@1.0.0, optional@0.1.3, buffer-to-vinyl@1.0.0, through2@0.6.5, meow@3.1.0, concat-stream@1.4.10, stream-combiner2@1.0.2, imagemin-svgo@4.1.2, vinyl-fs@1.0.0, imagemin-jpegtran@4.2.0, imagemin-optipng@4.3.0, imagemin-gifsicle@4.2.0)
```
How would you recommend I "fix my permissions"? I'm not very fluent with terminal and permissions quite yet

**Comment by kevva** [comment]
You need to give me the output from installing `imagemin-pngquant` since that's what failing.

**Comment by shaneparsons** [comment]
I couldn't find any "pre-build" output re: pngquant, so I re-installed it and all seems to be working again.

It still doesn't explain why it stopped working in the first place, but that's in the past.

Thanks for your help.

**Comment by kevva** [comment]
Sweet, happy you got it working :).

**Comment by shaneparsons** [comment]
Thanks for the help with fixing permissions too btw!

**Comment by davidcalhoun** [comment]
Had a similar problem - I think I had a botched install somehow.  Deleted the entire `node_modules` directory and re-installed (`yarn install`)
