### ISSUE TITLE
Proxy problems with imagemin 0.9.4

### ISSUE THREAD

**Issue by Icydillic** [imagemin/imagemin#110]
We have a problem using imagemin in the specified version behind a corporate proxy. All other dependencies install without problems and using wget to access the urls is working too, so I'm pretty sure the proxy is configured correctly. With version 0.8.1 it was working fine.
Does someone encountered the same problem?
This is our output when we try to do npm install

> jpegtran-bin@3.0.2 postinstall /home/jenkins/workspace/spexAdmin-production/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin
> node lib/install.js

  Request to https://raw.github.com/imagemin/jpegtran-bin/3.0.2/vendor/linux/x64/jpegtran failed
  jpegtran pre-build test failed
  compiling from source
  ✖ GotError: Request to http://downloads.sourceforge.net/project/libjpeg-turbo/1.4.0/libjpeg-turbo-1.4.0.tar.gz failed
    at ClientRequest.<anonymous> (/home/jenkins/workspace/spexAdmin-production/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/node_modules/bin-build/node_modules/download/node_modules/got/index.js:177:7)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.emit (events.js:95:17)
    at Socket.socketErrorListener (http.js:1551:9)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
Caused By: Error: connect ETIMEDOUT
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:19)

> gifsicle@3.0.1 postinstall /home/jenkins/workspace/spexAdmin-production/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle
> node lib/install.js

  Request to https://raw.github.com/imagemin/gifsicle-bin/3.0.1/vendor/linux/x64/gifsicle failed
  gifsicle pre-build test failed
  compiling from source
  ✖ GotError: Request to http://www.lcdf.org/gifsicle/gifsicle-1.87.tar.gz failed
    at ClientRequest.<anonymous> (/home/jenkins/workspace/spexAdmin-production/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/got/index.js:177:7)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.emit (events.js:95:17)
    at Socket.socketErrorListener (http.js:1551:9)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
Caused By: Error: connect ETIMEDOUT
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:19)

> optipng-bin@3.0.2 postinstall /home/jenkins/workspace/spexAdmin-production/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin
> node lib/install.js

  Request to https://raw.github.com/imagemin/optipng-bin/3.0.2/vendor/linux/x64/optipng failed
  optipng pre-build test failed
  compiling from source
  ✖ GotError: Request to http://downloads.sourceforge.net/project/optipng/OptiPNG/optipng-0.7.5/optipng-0.7.5.tar.gz failed
    at ClientRequest.<anonymous> (/home/jenkins/workspace/spexAdmin-production/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-build/node_modules/download/node_modules/got/index.js:177:7)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.emit (events.js:95:17)
    at Socket.socketErrorListener (http.js:1551:9)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
Caused By: Error: connect ETIMEDOUT
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:19)

**Comment by shinnn** [comment]
> with imagemin 0.9.4

No `0.9.4`.

```
$ npm view imagemin versions
 
[ '0.1.0',
  '0.1.1',
  '0.1.2',
  '0.1.3',
  '0.2.4',
  '0.4.5',
  '0.4.6',
  '0.4.7',
  '0.4.8',
  '0.4.9',
  '1.0.0',
  '1.0.1',
  '1.0.2',
  '1.0.3',
  '1.0.4',
  '1.0.5',
  '2.0.0',
  '2.0.1',
  '2.1.0',
  '2.1.1',
  '2.1.2',
  '2.2.0',
  '2.2.1',
  '3.0.0',
  '3.1.0',
  '3.2.0' ]
```

**Comment by kevva** [comment]
I'm guessing you're behind a proxy? See https://github.com/kevva/download/issues/64.
