### ISSUE TITLE
Optimizer Files give Timeout on install

### ISSUE THREAD

**Issue by Sly777** [imagemin/imagemin#112]
Hi all,

Npm doesn't install plugin correctly because Optimizers' files (.7z or source files from sourgeforge) give timeout error when install this plugin. I tried on two computers that has different network and also i checked them with some ping websites.

Error Output:

```
$ npm install grunt-contrib-imagemin
-
> optipng-bin@3.0.2 postinstall C:\project\test\node_modules\grunt-contrib-imagemin\node_modules\imagemin\node_modules\imagemin-optipng\node_modules\optipng-bin
> node lib/install.js

  ‼ Request to https://raw.github.com/imagemin/optipng-bin/3.0.2/vendor/win/optipng.exe failed
  ‼ optipng pre-build test failed
  i compiling from source
  × GotError: Request to http://downloads.sourceforge.net/project/optipng/OptiPNG/optipng-0.7.5/optipng-0.7.5.tar.gz failed
    at ClientRequest.<anonymous> (C:\project\test\node_modules\grunt-contrib-imagemin\node_modules\imagemin\node_modules\imagemin-optipng\node_modules\optipng-bin\node_modules\bin-build\node_modules\download\node_modules\got\index.js:177:7)
    at ClientRequest.g (events.js:199:16)
    at ClientRequest.emit (events.js:107:17)
    at Socket.socketErrorListener (_http_client.js:272:9)
    at Socket.emit (events.js:107:17)
    at net.js:451:14
    at process._tickCallback (node.js:355:11)
Caused By: Error: connect ETIMEDOUT
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:983:19)

> jpegtran-bin@3.0.2 postinstall C:\project\test\node_modules\grunt-contrib-imagemin\node_modules\imagemin\node_modules\imagemin-jpegtran\node_modules\jpegtran-bin
> node lib/install.js

  ‼ Request to https://raw.github.com/imagemin/jpegtran-bin/3.0.2/vendor/win/x64/libjpeg-62.dll failed
  ‼ jpegtran pre-build test failed
  i compiling from source
  × GotError: Request to http://downloads.sourceforge.net/project/libjpeg-turbo/1.4.0/libjpeg-turbo-1.4.0.tar.gz failed
    at ClientRequest.<anonymous> (C:\project\test\node_modules\grunt-contrib-imagemin\node_modules\imagemin\node_modules\imagemin-jpegtran\node_modules\jpegtran-bin\node_modules\bin-build\node_modules\download\node_modules\got\index.js:177:7)
    at ClientRequest.g (events.js:199:16)
    at ClientRequest.emit (events.js:107:17)
    at Socket.socketErrorListener (_http_client.js:272:9)
    at Socket.emit (events.js:107:17)
    at net.js:451:14
    at process._tickCallback (node.js:355:11)
Caused By: Error: connect ETIMEDOUT
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:983:19)

> gifsicle@3.0.1 postinstall C:\project\test\node_modules\grunt-contrib-imagemin\node_modules\imagemin\node_modules\imagemin-gifsicle\node_modules\gifsicle
> node lib/install.js

  ‼ Request to https://raw.github.com/imagemin/gifsicle-bin/3.0.1/vendor/win/x64/gifsicle.exe failed
  ‼ gifsicle pre-build test failed
  i compiling from source
  × GotError: Request to http://www.lcdf.org/gifsicle/gifsicle-1.87.tar.gz failed
    at ClientRequest.<anonymous> (C:\project\test\node_modules\grunt-contrib-imagemin\node_modules\imagemin\node_modules\imagemin-gifsicle\node_modules\gifsicle\node_modules\bin-build\node_modules\download\node_modules\got\index.js:177:7)
    at ClientRequest.g (events.js:199:16)
    at ClientRequest.emit (events.js:107:17)
    at Socket.socketErrorListener (_http_client.js:272:9)
    at Socket.emit (events.js:107:17)
    at net.js:451:14
    at process._tickCallback (node.js:355:11)
Caused By: Error: connect ETIMEDOUT
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:983:19)
grunt-contrib-imagemin@0.9.4 node_modules\grunt-contrib-imagemin
├── gulp-rename@1.2.2
├── async@0.9.2
├── chalk@1.0.0 (escape-string-regexp@1.0.3, ansi-styles@2.0.1, supports-color@1.3.1, has-ansi@1.0.3, strip-ansi@2.0.1)
├── pretty-bytes@1.0.4 (get-stdin@4.0.1, meow@3.3.0)
└── imagemin@3.2.0 (get-stdin@4.0.1, path-exists@1.0.0, optional@0.1.3, buffer-to-vinyl@1.0.0, through2@0.6.5, meow@3.3.0, stream-combiner2@1.0.2, concat-stream@1.5.0, vinyl-fs@1.0.0, imagemin-svgo@4.1.2, imagemin-optipng@4.3.0, imagemin-jpegtran@4.2.0, imagemin-gifsicle@4.2.0)
```

**Comment by shinnn** [comment]
I cannot reproduce that. Can you show us the output of these commands?

```
$ node -v
$ npm -v 
```

**Comment by Sly777** [comment]
@shinnn 

node -v
v0.12.1

npm -v
2.5.1

**Comment by orangejuicy** [comment]
Same behaviour. Ordinal wget of binary or sources work successfully.
I'm behind proxy, and all other npm packages successfully installed.

**Comment by kevva** [comment]
https://github.com/kevva/download/issues/64
