### ISSUE TITLE
Gulp task fails on imagemin-gifsicle, vendor folder not installed

### ISSUE THREAD

**Issue by zvennn** [imagemin/imagemin#116]
Hi,

I tried to reinstall several times and get the pre-build test success. But gulp keeps having this error:

`Error: spawn /node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/vendor/gifsicle ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)`

tried emptying npm cache and reinstall. Tried installing gifsicle seperately. Fixed my permissions on the directory, but nothing works.

version gulp: ^3.8.5
version gulp-imagemin: ^2.3.0
version imagemin-pngquant: ^4.1.0

**Comment by zvennn** [comment]
did the whole step by step installation again and now it worked (probably because I fixed permissions after the first installation, now installed with fixed permissions)
