### ISSUE TITLE
All the dependencies fail due to new stream-combiner2

### ISSUE THREAD

**Issue by DrEnter** [imagemin/imagemin#127]
Starting a couple hours ago, all the imagemin-* dependencies fail to work.  When installing, we get an error like the following:

```
$ npm i imagemin
npm WARN engine imagemin@3.2.0: wanted: {"node":">=0.10.0","npm":">=2.1.5"} (current: {"node":"0.10.40","npm":"1.4.28"})
/
> gifsicle@3.0.1 postinstall /home/rof/src/bitbucket.org/vgtf/cnn-michonne-app/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle
> node lib/install.js

  ⚠ Invalid non-string/buffer chunk
  ⚠ gifsicle pre-build test failed
  ℹ compiling from source
  ✖ TypeError: Invalid non-string/buffer chunk
    at chunkInvalid (/home/rof/src/bitbucket.org/vgtf/cnn-michonne-app/node_modules/imagemin/node_modules/stream-combiner2/node_modules/readable-stream/lib/_stream_readable.js:421:10)
    at readableAddChunk (/home/rof/src/bitbucket.org/vgtf/cnn-michonne-app/node_modules/imagemin/node_modules/stream-combiner2/node_modules/readable-stream/lib/_stream_readable.js:176:12)
    at DuplexWrapper.Readable.push (/home/rof/src/bitbucket.org/vgtf/cnn-michonne-app/node_modules/imagemin/node_modules/stream-combiner2/node_modules/readable-stream/lib/_stream_readable.js:162:10)
    at DuplexWrapper._forwardRead (/home/rof/src/bitbucket.org/vgtf/cnn-michonne-app/node_modules/imagemin/node_modules/stream-combiner2/node_modules/duplexer2/index.js:95:10)
    at DestroyableTransform.<anonymous> (/home/rof/src/bitbucket.org/vgtf/cnn-michonne-app/node_modules/imagemin/node_modules/stream-combiner2/node_modules/duplexer2/index.js:54:10)
    at DestroyableTransform.emit (events.js:92:17)
    at emitReadable_ (/home/rof/src/bitbucket.org/vgtf/cnn-michonne-app/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-build/node_modules/decompress/node_modules/decompress-unzip/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:460:10)
    at emitReadable (/home/rof/src/bitbucket.org/vgtf/cnn-michonne-app/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-build/node_modules/decompress/node_modules/decompress-unzip/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:454:7)
    at readableAddChunk (/home/rof/src/bitbucket.org/vgtf/cnn-michonne-app/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-build/node_modules/decompress/node_modules/decompress-unzip/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:209:11)
    at DestroyableTransform.Readable.push (/home/rof/src/bitbucket.org/vgtf/cnn-michonne-app/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-build/node_modules/decompress/node_modules/decompress-unzip/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:162:10)

> jpegtran-bin@3.0.5 postinstall /home/rof/src/bitbucket.org/vgtf/cnn-michonne-app/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin
> node lib/install.js

  ⚠ Invalid non-string/buffer chunk
  ⚠ jpegtran pre-build test failed
  ℹ compiling from source
  ✖ TypeError: Invalid non-string/buffer chunk
...
```

The problem appears to be a new version of stream-combiner2 (1.1.0).  Reverting that back to 1.0.2 and everything is fine.

Might be worth pinning that dependency.

**Comment by shinnn** [comment]
Thanks. This will be fixed after [decompress](https://github.com/kevva/decompress) author publish a new version. https://github.com/kevva/decompress/commit/7c9980cd06978481909f238d2281efa58c9b5916
