### ISSUE TITLE
broken since stream-combiner2 update

### ISSUE THREAD

**Issue by mziwisky** [imagemin/imagemin#132]
just cloned imagemin and tried running `npm test`, and "optimize a SVG" fails as follows:

```
  ✖ optimize a SVG   TypeError: Invalid non-string/buffer chunk
/Users/mziwisky/repos/imagemin/test/test.js:91
		t.assert(files[0].contents.length < src.length, files[0].contents.length);
		              ^
TypeError: Cannot read property '0' of undefined
    at DuplexWrapper.<anonymous> (/Users/mziwisky/repos/imagemin/test/test.js:91:17)
    at DuplexWrapper.emit (events.js:107:17)
    at Through2.<anonymous> (/Users/mziwisky/repos/imagemin/node_modules/stream-combiner2/node_modules/duplexer2/index.js:65:19)
    at Through2.emit (events.js:129:20)
    at afterTransform (/Users/mziwisky/repos/imagemin/node_modules/imagemin-svgo/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:95:19)
    at TransformState.afterTransform (/Users/mziwisky/repos/imagemin/node_modules/imagemin-svgo/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:79:12)
    at Through2._transform (/Users/mziwisky/repos/imagemin/node_modules/imagemin-svgo/index.js:51:4)
    at Through2.Transform._read (/Users/mziwisky/repos/imagemin/node_modules/imagemin-svgo/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Through2.Transform._write (/Users/mziwisky/repos/imagemin/node_modules/imagemin-svgo/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/mziwisky/repos/imagemin/node_modules/imagemin-svgo/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
npm ERR! Test failed.  See above for more details.
```

this appears to be related to the recent bump of `stream-combiner2` from 1.0.2 to 1.1.1.  if i change the stream-combiner2 dependency in package.json to a hard 1.0.2, the tests pass (but I get a lot of `npm WARN unmet dependency` messages due to other dependencies depending on v1.1.1)

**Comment by tcoopman** [comment]
I suspect this has something to do with this update in stream-combiner2: https://github.com/substack/stream-combiner2/commit/5da8e716dc0164e1f5d69506dd89d82a01774759

**Comment by shinnn** [comment]
Already fixed in imagemin v3.2.1.

**Comment by mziwisky** [comment]
ah, sorry, didn't see the closed issue, nor the 3.2.1 tag, and was running tests on master. thanks for the fix! :+1:

**Comment by shinnn** [comment]
Also fixed in `master`. https://github.com/imagemin/imagemin/commit/23aa67597ade920f55df51fa812d91ab2dccfa99

**Comment by opatut** [comment]
+1

**Comment by dopesong** [comment]
I think something happened again: https://github.com/sindresorhus/gulp-imagemin/issues/161

**Comment by witoldszpur** [comment]
yes same issue again.

**Comment by shinnn** [comment]
> same issue

No. :point_right: https://github.com/imagemin/imagemin-pngquant/issues/21

**Comment by dopesong** [comment]
Saw it already ;) Lot of mentions :+1:
