### ISSUE TITLE
ECONNRESET error

### ISSUE THREAD

**Issue by shayan786** [imagemin/imagemin#153]
Couldn't find this anywhere..keeps failing on a digital ocean ubuntu instance....works find in local when building, fails production build.

```
node: 5.0.0
npm: 3.3.6
```

└─┬ gulp-imagemin@2.4.0
  └── imagemin@4.0.0 

```
[22:45:13] Starting 'images'...
[22:45:13] Finished 'images' after 15 ms

events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: read ECONNRESET
    at exports._errnoException (util.js:860:11)
    at Pipe.onread (net.js:544:26)
```

```
gulp.task('images', function () {
  gulp.src(dirs.images)
    .pipe(imagemin({
      'progressive': true,
      'svgoPlugins': [
        {removeViewBox: false},
        {cleanupIDs: false}
      ],
      use: [pngquant()]
    }))
    .pipe(gulp.dest(dirs.public + '/images'));
});
```

**Comment by shinnn** [comment]
First you should return the `gulp.src` stream inside a gulp task.

```diff
-  gulp.src(dirs.images)
+  return gulp.src(dirs.images)
```

**Comment by shayan786** [comment]
makes not difference, still get the same issue.

```
[01:52:27] Using gulpfile ~/nanis-dough/Gulpfile.js
[01:52:27] Starting 'images'...

events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: read ECONNRESET
    at exports._errnoException (util.js:860:11)
    at Pipe.onread (net.js:544:26)
```

**Comment by shinnn** [comment]
> makes not difference

No. It solved the other problem. https://github.com/gulpjs/gulp/blob/master/docs/API.md#async-task-support
