### ISSUE TITLE
mozjpeg pre-build test failed

### ISSUE THREAD

**Issue by bshack** [imagemin/imagemin#168]
mozjpeg is failing for me on OS X 10.11:

```
optipng-bin@3.1.1 postinstall /Users/xxx/Sites/white-label/node_modules/gulp-imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin
> node lib/install.js

  ✔ optipng pre-build test passed successfully
 
> mozjpeg@4.1.1 postinstall /Users/xxx/Sites/white-label/node_modules/gulp-imagemin/node_modules/imagemin-mozjpeg/node_modules/mozjpeg
> node lib/install.js

  ⚠ The `/Users/xxx/Sites/white-label/node_modules/gulp-imagemin/node_modules/imagemin-mozjpeg/node_modules/mozjpeg/vendor/cjpeg` binary doesn't seem to work correctly
  ⚠ mozjpeg pre-build test failed
  ℹ compiling from source
  ✖ Error: autoreconf -fiv && ./configure --disable-shared --prefix="/Users/xxx/Sites/white-label/node_modules/gulp-imagemin/node_modules/imagemin-mozjpeg/node_modules/mozjpeg/vendor" --bindir="/Users/xxx/Sites/white-label/node_modules/gulp-imagemin/node_modules/imagemin-mozjpeg/node_modules/mozjpeg/vendor" --libdir="/Users/xxx/Sites/white-label/node_modules/gulp-imagemin/node_modules/imagemin-mozjpeg/node_modules/mozjpeg/vendor" && make --jobs=8 && make install --jobs=8
Command failed: /bin/sh -c autoreconf -fiv
/bin/sh: autoreconf: command not found

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:477:12)
 
> gifsicle@3.0.3 postinstall /Users/xxx/Sites/white-label/node_modules/gulp-imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle
> node lib/install.js

  ✔ gifsicle pre-build test passed successfully
```

**Comment by shinnn** [comment]
@bshack Did you read the previous issue?

**Comment by shinnn** [comment]
```
$ nasm -v
```

**Comment by bshack** [comment]
NASM version 0.98.40 (Apple Computer, Inc. build 11) compiled on Feb 10 2016

**Comment by shinnn** [comment]
https://github.com/mozilla/mozjpeg/blob/da75d56d6c71fcf33cca2118065af13409fe35d4/BUILDING.txt#L21-L22

Can you update NASM and try installing again?

**Comment by bshack** [comment]
NASM version 2.12.01 compiled on Mar 23 2016

```
 ✔ optipng pre-build test passed successfully
 
> mozjpeg@4.1.1 postinstall /Users/billshackelford/Sites/white-label/node_modules/gulp-imagemin/node_modules/imagemin-mozjpeg/node_modules/mozjpeg
> node lib/install.js

  ⚠ The `/Users/billshackelford/Sites/white-label/node_modules/gulp-imagemin/node_modules/imagemin-mozjpeg/node_modules/mozjpeg/vendor/cjpeg` binary doesn't seem to work correctly
  ⚠ mozjpeg pre-build test failed
  ℹ compiling from source
  ✖ Error: autoreconf -fiv && ./configure --disable-shared --prefix="/Users/billshackelford/Sites/white-label/node_modules/gulp-imagemin/node_modules/imagemin-mozjpeg/node_modules/mozjpeg/vendor" --bindir="/Users/billshackelford/Sites/white-label/node_modules/gulp-imagemin/node_modules/imagemin-mozjpeg/node_modules/mozjpeg/vendor" --libdir="/Users/billshackelford/Sites/white-label/node_modules/gulp-imagemin/node_modules/imagemin-mozjpeg/node_modules/mozjpeg/vendor" && make --jobs=8 && make install --jobs=8
Command failed: /bin/sh -c autoreconf -fiv
/bin/sh: autoreconf: command not found

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:477:12)
 
> gifsicle@3.0.3 postinstall /Users/billshackelford/Sites/white-label/node_modules/gulp-imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle
> node lib/install.js

  ✔ gifsicle pre-build test passed successfully
```

**Comment by shinnn** [comment]
> ```
> /bin/sh: autoreconf: command not found
> ```

http://stackoverflow.com/questions/9575989/install-autoreconf-on-osx-lion

Anyway, the prebuilt binary should work. In my OS X 10.11.4 (15E65) `npm install mozjpeg` shows the message "optipng pre-build test passed successfully". I don't know the root cause of the installation failure in your OS.

**Comment by bshack** [comment]
Mine is a fresh install of is x 10.11.4

**Comment by bshack** [comment]
I also have the latest Xcode updates

**Comment by nathangaw** [comment]
Hi - I'm getting exactly the same error on OS X 10.11.4, with NASM version 2.12.01.

**Comment by shinnn** [comment]
@bshack @nathangaw Could you try to build mozjpeg from the v3.1 source in your OS https://github.com/mozilla/mozjpeg/releases/tag/v3.1, then provide me the built binary?

**Comment by shinnn** [comment]
If you successfully build the mozjpeg binary and it works on both my Mac and yours, I'll replace the current binary with the newly built one.

**Comment by mike3run** [comment]
I'm having the same error, it used to work fine, but after the Xcode Update this got broken 😢

**Comment by bshack** [comment]
@shinnn are you able to reproduce this issue after installing all the latest xcode updates?

**Comment by shinnn** [comment]
@bshack No.

Also I added OSX test to mozjpeg npm package in https://github.com/imagemin/mozjpeg-bin/commit/b0bd5cdd7fc276891701642584ad9bb2422178a0. it runs with OSX v10.11 and [Xcode v7.3](https://docs.travis-ci.com/user/osx-ci-environment/#Xcode-7.3) and, in contrast to @mike3run's comment https://github.com/imagemin/imagemin/issues/168#issuecomment-217732098, it passes the build test.

**Comment by bshack** [comment]
What is your Xcode version?

**Comment by bshack** [comment]
hmm.. not sure what is up. I am rolling back to 2.x.x for my stuff.

**Comment by mike3run** [comment]
I can tell you what was the difference with mine a probably the OP.

I always npm-cache install to help with load times, but this time besides the xcode update i had deleted all of my node projects so the install was made from scratch and no catching was done.

Then I think that's where the problem is, try running that without having any other functional imagemin on your computer :)

**Comment by mike3run** [comment]
Try running also `node node_modules/mozjpeg/lib/install.js` to try the build manually

**Comment by chrisvanpatten** [comment]
I got a similar error. Here's what I did to fix it; hopefully this helps someone else!

1. Update Xcode command line tools to latest release
2. `brew install nasm` (I was using the bundled OS X version 0.98.40)
3. `npm cache clean`
4. `npm install`

Still getting an error with the cjpeg binary, but the build from source works now.

**Comment by mike3run** [comment]
What @chrisvanpatten did worked for me as well.

The binary fails but then the build from source works. :)

**Comment by dangolol** [comment]
How to uninstall nasm on mac ?  My nams version is 0.98. I install nams from brew is not work, still 0.98

**Comment by dangolol** [comment]
Library/WebServer/Documents/common/node_modules/gulp-imagemin/node_modules/imagemin-mozjpeg/node_modules/mozjpeg/vendor" --libdir="/Library/WebServer/Documents/common/node_modules/gulp-imagemin/node_modules/imagemin-mozjpeg/node_modules/mozjpeg/vendor" && make --jobs=8 && make install --jobs=8
Command failed: /bin/sh -c ./configure --disable-shared --prefix="/Library/WebServer/Documents/common/node_modules/gulp-imagemin/node_modules/imagemin-mozjpeg/node_modules/mozjpeg/vendor" --bindir="/Library/WebServer/Documents/common/node_modules/gulp-imagemin/node_modules/imagemin-mozjpeg/node_modules/mozjpeg/vendor" --libdir="/Library/WebServer/Documents/common/node_modules/gulp-imagemin/node_modules/imagemin-mozjpeg/node_modules/mozjpeg/vendor"
./configure: line 13758: syntax error near unexpected token `libpng,'
./configure: line 13758: `PKG_CHECK_MODULES(libpng, libpng, HAVE_LIBPNG=1,'

**Comment by afzal273** [comment]
How do you build from source on OS X? 

I'm still getting - /node_modules/imagemin-mozjpeg/node_modules/mozjpeg/vendor/cjpeg` binary doesn't seem to work correctly

 node node_modules/imagemin-mozjpeg/node_modules/mozjpeg/lib/install.js 

  ⚠ mozjpeg pre-build test failed
  ℹ compiling from source
  ✖ Error: autoreconf -fiv && ./configure --disable-shared --prefix=/node_modules/imagemin-mozjpeg/node_modules/mozjpeg/vendor" --bindir="/node_modules/imagemin-mozjpeg/node_modules/mozjpeg/vendor" --libdir="./node_modules/imagemin-mozjpeg/node_modules/mozjpeg/vendor" && make --jobs=8 && make install --jobs=8
Command failed: /bin/sh -c autoreconf -fiv
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal  --output=aclocal.m4t
Can't exec "aclocal": No such file or directory at /usr/local/Cellar/autoconf/2.69/share/autoconf/Autom4te/FileUtils.pm line 326.
autoreconf: failed to run aclocal: No such file or directory

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

**Comment by mike3run** [comment]
You can try what @chrisvanpatten said 2 comments above yours or you could also use node LTS version which is 4.4.5 

Apparently there are tons of bugs running Node 6.0 +

So unless you're an active node dev you should stay on 4.4.5 :)

**Comment by afzal273** [comment]
Already did what @chrisvanpatten said and my node version is 4.4.4.

Chris also says to do build from source. How do you do that?

**Comment by mike3run** [comment]
Okay so just try to npm install imagemin again :)

That worked for me but you could also cd into node_modules > mozjpeg > test and run node test

That should try to build it but you need to have done what @chrisvanpatten said

**Comment by afzal273** [comment]
Still getting 
node install.js 
  ⚠ The `/Users/asyed/Dropbox/Code/udacity/frontEndNanoDegree/websiteOptimization/fend-website-optimization-project/node_modules/imagemin-mozjpeg/node_modules/mozjpeg/vendor/cjpeg` binary doesn't seem to work correctly
  ⚠ mozjpeg pre-build test failed
  ℹ compiling from source


Command failed: /bin/sh -c autoreconf -fiv
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal  --output=aclocal.m4t
Can't exec "aclocal": No such file or directory at /usr/local/Cellar/autoconf/2.69/share/autoconf/Autom4te/FileUtils.pm line 326.
autoreconf: failed to run aclocal: No such file or directory

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

grunt imagemin
Running "imagemin:static" (imagemin) task
Fatal error: stream.on is not a function

:-/ 

Anyhow I got the images I wanted from google page insights.

**Comment by artmatsak** [comment]
`cjpeg` managed to build from source after I installed a newer version `nasm` via MacPorts. However, `cjpeg` now exits with a segmentation fault when invoked from a parent dir, or is unable to process a JPEG file when invoked from its dir:

```
$ ./node_modules/imagemin-mozjpeg/node_modules/mozjpeg/vendor/cjpeg ~/Downloads/test.jpg
Segmentation fault: 11
$ cd node_modules/imagemin-mozjpeg/node_modules/mozjpeg/vendor
$ cjpeg ~/Downloads/test.jpg
Unrecognized input file format --- perhaps you need -targa
```

Any suggestions please? OS X 10.12 here.

**Comment by artmatsak** [comment]
Update: Installing `mozjpeg` first via `npm install mozjpeg` also leads to building from source but seems to produce a non-faulty `cjpeg`.

**Comment by wmartins** [comment]
I don't know if @bshack is still having problems with that, but I was struggling with the same problem yesterday and I think that I've found a solution.

**My Scenario**: building a project that uses imagemin inside a docker container using alpine linux.

**Solution**: install the following alpine packages:

- libpng-dev
- autoconf
- automake
- make
- g++
- libtool
- nasm

After installing that, I was able to compile the binaries.

I don't know if it helps, but I'm adding it here, so anyone can try this when having the same problems.

**Comment by westyby** [comment]
This bug reproduced on CentOS 6.8 witn node.js v6.9.4. 
But when I install ``yum install wget autoconf automake gcc nasm libtool``, I successfully compiled mozjpeg

 mozjpeg@4.1.1 postinstall /home/bitrix/serv_opti/node_modules/mozjpeg
 node lib/install.js

  ⚠ The `/home/bitrix/serv_opti/node_modules/mozjpeg/vendor/cjpeg` binary doesn't seem to work correctly
  ⚠ mozjpeg pre-build test failed
  ℹ compiling from source
  ✔ mozjpeg built successfully

**Comment by ahgittin** [comment]
This fixed the source build for me on Mac Sierra:

`sudo port install automake autoconf libtool dpkg pkgconfig nasm`

**Comment by jmeit** [comment]
On Ubuntu 16.04, `sudo apt install nasm` worked for me!

**Comment by LitvinenkoEvgeny** [comment]
hey guys did you try this ? 
https://github.com/mozilla/mozjpeg/issues/99#issuecomment-52628719

**Comment by desmond132518** [comment]
On MacOS 10.11.6, I did this

`sudo port install automake autoconf libtool dpkg pkgconfig nasm libpng`

**Comment by genio** [comment]
Still no dice here on CentOS 7.

```bash
# cat /etc/redhat-release 
CentOS Linux release 7.4.1708 (Core)
```

```bash
# yum install nasm gcc make autoconf automake m4 libtool wget curl libjpeg-turbo-utils libjpeg-turbo-devel libpng libpng-devel
Loaded plugins: fastestmirror, priorities, replace, versionlock
Loading mirror speeds from cached hostfile
 * base: mirror.pac-12.org
 * epel: mirrors.cat.pdx.edu
 * extras: mirrors.cat.pdx.edu
 * updates: mirrors.kernel.org
 * webtatic: uk.repo.webtatic.com
Package nasm-2.10.07-7.el7.x86_64 already installed and latest version
Package gcc-4.8.5-16.el7_4.1.x86_64 already installed and latest version
Package 1:make-3.82-23.el7.x86_64 already installed and latest version
Package autoconf-2.69-11.el7.noarch already installed and latest version
Package automake-1.13.4-3.el7.noarch already installed and latest version
Package m4-1.4.16-10.el7.x86_64 already installed and latest version
Package libtool-2.4.2-22.el7_3.x86_64 already installed and latest version
Package wget-1.14-15.el7_4.1.x86_64 already installed and latest version
Package curl-7.29.0-42.el7_4.1.x86_64 already installed and latest version
Package libjpeg-turbo-utils-1.2.90-5.el7.x86_64 already installed and latest version
Package libjpeg-turbo-devel-1.2.90-5.el7.x86_64 already installed and latest version
Package 2:libpng-1.5.13-7.el7_2.x86_64 already installed and latest version
Package 2:libpng-devel-1.5.13-7.el7_2.x86_64 already installed and latest version
Nothing to do
```
and then:

```bash
# npm install -g mozjpeg
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
/usr/bin/mozjpeg -> /usr/lib/node_modules/mozjpeg/cli.js

> mozjpeg@5.0.0 postinstall /usr/lib/node_modules/mozjpeg
> node lib/install.js

  ⚠ EACCES: permission denied, mkdir '/usr/lib/node_modules/mozjpeg/vendor'
  ⚠ mozjpeg pre-build test failed
  ℹ compiling from source
/usr/lib/node_modules/mozjpeg/node_modules/onetime/index.js:15
				throw new Error(fnName + ' can only be called once.');
				^

Error: callback() can only be called once.
    at onetime (/usr/lib/node_modules/mozjpeg/node_modules/onetime/index.js:15:11)
    at /usr/lib/node_modules/mozjpeg/node_modules/download/index.js:156:5
    at ConcatStream.<anonymous> (/usr/lib/node_modules/mozjpeg/node_modules/concat-stream/index.js:36:43)
    at ConcatStream.emit (events.js:165:20)
    at finishMaybe (/usr/lib/node_modules/mozjpeg/node_modules/readable-stream/lib/_stream_writable.js:620:14)
    at endWritable (/usr/lib/node_modules/mozjpeg/node_modules/readable-stream/lib/_stream_writable.js:628:3)
    at ConcatStream.Writable.end (/usr/lib/node_modules/mozjpeg/node_modules/readable-stream/lib/_stream_writable.js:584:41)
    at DuplexWrapper.onend (/usr/lib/node_modules/mozjpeg/node_modules/readable-stream/lib/_stream_readable.js:577:10)
    at Object.onceWrapper (events.js:255:19)
    at DuplexWrapper.emit (events.js:165:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mozjpeg@5.0.0 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mozjpeg@5.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-02-13T03_25_29_915Z-debug.log
```

**Comment by FernandoMiguel** [comment]
anyone ever figured how to natively install this in alpine without requiring to build from source?

**Comment by andot** [comment]
I get the same error:

```log
sudo npm install mozjpeg -g
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
/usr/bin/mozjpeg -> /usr/lib/node_modules/mozjpeg/cli.js

> mozjpeg@5.0.0 postinstall /usr/lib/node_modules/mozjpeg
> node lib/install.js

  ⚠ EACCES: permission denied, mkdir '/usr/lib/node_modules/mozjpeg/vendor'
  ⚠ mozjpeg pre-build test failed
  ℹ compiling from source
/usr/lib/node_modules/mozjpeg/node_modules/onetime/index.js:15
                                throw new Error(fnName + ' can only be called once.');
                                ^

Error: callback() can only be called once.
    at onetime (/usr/lib/node_modules/mozjpeg/node_modules/onetime/index.js:15:11)
    at /usr/lib/node_modules/mozjpeg/node_modules/download/index.js:156:5
    at ConcatStream.<anonymous> (/usr/lib/node_modules/mozjpeg/node_modules/concat-stream/index.js:36:43)
    at ConcatStream.emit (events.js:185:15)
    at finishMaybe (/usr/lib/node_modules/mozjpeg/node_modules/readable-stream/lib/_stream_writable.js:620:14)
    at endWritable (/usr/lib/node_modules/mozjpeg/node_modules/readable-stream/lib/_stream_writable.js:628:3)
    at ConcatStream.Writable.end (/usr/lib/node_modules/mozjpeg/node_modules/readable-stream/lib/_stream_writable.js:584:41)
    at DuplexWrapper.onend (/usr/lib/node_modules/mozjpeg/node_modules/readable-stream/lib/_stream_readable.js:577:10)
    at Object.onceWrapper (events.js:272:13)
    at DuplexWrapper.emit (events.js:185:15)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mozjpeg@5.0.0 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mozjpeg@5.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-03-19T11_29_33_714Z-debug.log
```

**Comment by thegbom** [comment]
Complements to okodor (https://github.com/mozilla/mozjpeg/issues/99):

sudo apt-get -y install build-essential cmake libtool autoconf automake m4 nasm pkg-config
sudo ldconfig /usr/lib
cd ~
wget https://github.com/mozilla/mozjpeg/archive/v3.1.tar.gz
tar -xvzf v3.1.tar.gz
cd mozjpeg-3.1/
autoreconf -fiv
mkdir build
cd build
sh ../configure
sudo make install

I supplemented a missing tar-statement. Running npm install after the steps above, I did not get the error.

**Comment by boogie4eva** [comment]
Great this worked for me .

**Comment by behroozam** [comment]
everytime i use npm for install nodejs dependencies , its stock on pre or post install scripts for install laravel-mix dependencies like gifsicle or mozjpeg  in ci for alpine docker sometime for poor internet connection ,sometime for iran sanctions that make github usless without proxy.
in that case i suggest install node-sass first and ignore scripts like this in your dockerfile
``RUN npm install --ignore-scripts && npm install node-sass --verbose && npm run  production --verbose && npm cache clean --force && rm -rf node_modules``

**Comment by xakzona** [comment]
It is helped me
https://stackoverflow.com/questions/25549536/error-while-loading-shared-libraries-libpng16

**Comment by debasishshanti** [comment]
@joepagan Many packages have OS specific implementations/versions. So when lock file is created in a particular OS it will reference the dependencies needed for that OS. I believe this is the problem

**Comment by frossi85** [comment]
Anyone that made this work in Linux Alpine could provide a Dockerfile and versions for npm, node and imagemin libs? I could not make it work in any way.

**Comment by dmitryuk** [comment]
```
FROM node:latest

RUN set -ex \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        autoconf \
        libtool \
        libpng-dev \
        pkg-config \
        nasm \
    && wget -q -O /tmp/libpng12.deb http://mirrors.kernel.org/ubuntu/pool/main/libp/libpng/libpng12-0_1.2.54-1ubuntu1_amd64.deb \
         && dpkg -i /tmp/libpng12.deb \
         && rm /tmp/libpng12.deb \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /tmp/*

RUN mkdir /var/www && chown -R node:node /var/www
WORKDIR /var/www
```

**Comment by frossi85** [comment]
@dmitryuk which imagemin and imagemin-mozjpeg versions are you using? Could you post the code to optimize that you are using because it seems that the interface change a lot from version to version and is not documented.

Also where are you storing images? Is that chown related to make imagemin work?

**Comment by dmitryuk** [comment]
I add webpack plugin this way only in production
```
new ImageMinPlugin({
        disable: process.env.NODE_ENV !== 'production',
        test: /\.(jpe?g|png|gif|svg)$/i,
        pngquant: {
            quality: 70
        },
        optipng: {},
        cacheFolder: '/var/www/cache/img'
    })
```

imagemin 6.1.0
imagemin-jpegtran 6.0.0

**Comment by dingyanhe** [comment]
> https://github.com/mozilla/mozjpeg/blob/da75d56d6c71fcf33cca2118065af13409fe35d4/BUILDING.txt#L21-L22
> 
> Can you update NASM and try installation again?

thanks. I need to install these dependencies

```md
==================
Build Requirements
==================

-- pkg-config
-- autoconf 2.56 or later
-- automake 1.7 or later
-- libtool 1.4 or later
   * If using Xcode 4.3 or later on OS X, autoconf and automake are no longer
     provided.  The easiest way to obtain them is from MacPorts
     (http://www.macports.org/).

-- NASM (if building x86 or x86-64 SIMD extensions)
   * 0.98, or 2.01 or later is required for a 32-bit build
   * NASM 2.00 or later is required for a 64-bit build
   * NASM 2.07 or later is required for a 64-bit build on OS X.  This can be
     obtained from MacPorts (http://www.macports.org/).

   The binary RPMs released by the NASM project do not work on older Linux
   systems, such as Red Hat Enterprise Linux 4.  On such systems, you can
   easily build and install NASM from a source RPM by downloading one of the
   SRPMs from

   http://www.nasm.us/pub/nasm/releasebuilds

   and executing the following as root:

     ARCH=`uname -m`
     rpmbuild --rebuild nasm-{version}.src.rpm
     rpm -Uvh /usr/src/redhat/RPMS/$ARCH/nasm-{version}.$ARCH.rpm

   NOTE: the NASM build will fail if texinfo is not installed.

-- GCC v4.1 (or later) or clang recommended

-- If building the TurboJPEG Java wrapper, JDK or OpenJDK 1.5 or later is
   required.  Some systems, such as Solaris 10 and later and Red Hat Enterprise
   Linux 5 and later, have this pre-installed.  On OS X 10.5 and later, it will
   be necessary to install the Java Developer Package, which can be downloaded
   from http://developer.apple.com/downloads (Apple ID required.)  For systems
   that do not have a JDK installed, you can obtain the Oracle Java Development
   Kit from http://www.java.com.

```

**Comment by LeleCao** [comment]
> I got a similar error. Here's what I did to fix it; hopefully this helps someone else!
> 
> 1. Update Xcode command line tools to latest release
> 2. `brew install nasm` (I was using the bundled OS X version 0.98.40, now using 2.11.08)
> 3. `npm cache clean`
> 4. `npm install`
> 
> Still getting an error with the cjpeg binary, but the build from source works now.

 I got a similar error.
> gatsby new doc
......
mozjpeg@7.0.0 postinstall /Users/caole/Desktop/Playground/doc/node_modules/mozjpeg
> node lib/install.js

  ⚠ write EPROTO 4497044928:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:

  ⚠ mozjpeg pre-build test failed
  ℹ compiling from source
  ✖ Error: Command failed: /bin/sh -c ./configure --enable-static --disable-shared --disable-dependency-tracking --with-jpeg8 libpng_LIBS='/usr/local/lib/libpng16.a -lz' --enable-static --prefix="/Users/caole/Desktop/Playground/doc/node_modules/mozjpeg/vendor" --bindir="/Users/caole/Desktop/Playground/doc/node_modules/mozjpeg/vendor" --libdir="/Users/caole/Desktop/Playground/doc/node_modules/mozjpeg/vendor"
configure: error: installation or configuration problem: assembler cannot create object files.
.....
-------------------------------------------------------------------
> gatsby info
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.15.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 88.0.4324.96
    Safari: 14.0
  npmPackages:
    gatsby: ^2.26.1 => 2.26.1
    gatsby-image: ^2.5.0 => 2.5.0
    gatsby-plugin-manifest: ^2.6.1 => 2.6.1
    gatsby-plugin-offline: ^3.4.0 => 3.4.0
    gatsby-plugin-react-helmet: ^3.4.0 => 3.4.0
    gatsby-source-filesystem: ^2.5.0 => 2.5.0
    gatsby-transformer-sharp: ^2.6.0 => 2.6.0
  npmGlobalPackages:
    gatsby-cli: 2.18.0

brew install nasm

Now it works properly。 My guess is that the error is related to the node version。
I hope it helps you

**Comment by jabir-hussain** [comment]
> It is not Alpine Linux, but may be it will help you to find a right solution .
> 
> ```
> FROM node:latest
> 
> RUN set -ex \
>     && apt-get update \
>     && apt-get install -y --no-install-recommends \
>         autoconf \
>         libtool \
>         libpng-dev \
>         pkg-config \
>         nasm \
>     && wget -q -O /tmp/libpng12.deb http://mirrors.kernel.org/ubuntu/pool/main/libp/libpng/libpng12-0_1.2.54-1ubuntu1_amd64.deb \
>          && dpkg -i /tmp/libpng12.deb \
>          && rm /tmp/libpng12.deb \
>     && rm -rf /var/lib/apt/lists/* \
>     && rm -rf /tmp/*
> 
> RUN mkdir /var/www && chown -R node:node /var/www
> WORKDIR /var/www
> ```

Thanks buddy, it solved my problem.

**Comment by whales2333** [comment]
I install homebrew successful; 
 then exec `brew install automake autoconf libtool dpkg pkgconfig nasm libpng`  timeout...

**Comment by wajeht** [comment]
i am also having the same issue on both mac and debian linux

**Comment by sdz123** [comment]
> On MacOS 10.11.6, I did this
> 
> `brew install automake autoconf libtool dpkg pkgconfig nasm libpng`

it works for me

**Comment by yongyiwong** [comment]
when I install mozjpeg globally and mozjepg --help, I got this error.
Environment: ` Ubuntu 22.04.1 LTS` 
Node version: 14.20.0

Here is the command I tried. 
```
npm -g install mozjpeg
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
/home/gf/.nvm/versions/node/v14.20.0/bin/mozjpeg -> /home/gf/.nvm/versions/node/v14.20.0/lib/node_modules/mozjpeg/cli.js

> mozjpeg@8.0.0 postinstall /home/gf/.nvm/versions/node/v14.20.0/lib/node_modules/mozjpeg
> node lib/install.js

+ mozjpeg@8.0.0
added 163 packages from 52 contributors in 49.827s

```

`mozjpeg --help`

```
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: spawn /home/gf/.nvm/versions/node/v14.20.0/lib/node_modules/mozjpeg/vendor/cjpeg ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:19)
    at onErrorNT (internal/child_process.js:472:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:12)
    at onErrorNT (internal/child_process.js:472:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /home/gf/.nvm/versions/node/v14.20.0/lib/node_modules/mozjpeg/vendor/cjpeg',
  path: '/home/gf/.nvm/versions/node/v14.20.0/lib/node_modules/mozjpeg/vendor/cjpeg',
  spawnargs: [ '--help' ]
}

```

Actually when post install,  I don't get any error or message. 
Also I have installed all packages `automake autoconf libtool dpkg pkgconfig nasm libpng`

Is there anyone faced this issue?

Thanks.

**Comment by MrBista** [comment]
same here, do you already solved it?

**Comment by MrBista** [comment]
> when I install mozjpeg globally and mozjepg --help, I got this error. Environment: ` Ubuntu 22.04.1 LTS` Node version: 14.20.0
> 
> Here is the command I tried.
> 
> ```
> npm -g install mozjpeg
> npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
> /home/gf/.nvm/versions/node/v14.20.0/bin/mozjpeg -> /home/gf/.nvm/versions/node/v14.20.0/lib/node_modules/mozjpeg/cli.js
> 
> > mozjpeg@8.0.0 postinstall /home/gf/.nvm/versions/node/v14.20.0/lib/node_modules/mozjpeg
> > node lib/install.js
> 
> + mozjpeg@8.0.0
> added 163 packages from 52 contributors in 49.827s
> ```
> 
> `mozjpeg --help`
> 
> ```
> events.js:377
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: spawn /home/gf/.nvm/versions/node/v14.20.0/lib/node_modules/mozjpeg/vendor/cjpeg ENOENT
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:19)
>     at onErrorNT (internal/child_process.js:472:16)
>     at processTicksAndRejections (internal/process/task_queues.js:82:21)
> Emitted 'error' event on ChildProcess instance at:
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:12)
>     at onErrorNT (internal/child_process.js:472:16)
>     at processTicksAndRejections (internal/process/task_queues.js:82:21) {
>   errno: -2,
>   code: 'ENOENT',
>   syscall: 'spawn /home/gf/.nvm/versions/node/v14.20.0/lib/node_modules/mozjpeg/vendor/cjpeg',
>   path: '/home/gf/.nvm/versions/node/v14.20.0/lib/node_modules/mozjpeg/vendor/cjpeg',
>   spawnargs: [ '--help' ]
> }
> ```
> 
> Actually when post install, I don't get any error or message. Also I have installed all packages `automake autoconf libtool dpkg pkgconfig nasm libpng`
> 
> Is there anyone faced this issue?
> 
> Thanks.

same here do you already solved it?

**Comment by oyeharry** [comment]
if you are using macOS, you could try following and run your installation again. It works for me. 

`arch -arm64e zsh`

**Comment by stivencardona** [comment]
Instance of change iTerm `Open with Rosseta` option you can try to run: `softwareupdate --install-rosetta`, this works to me

**Comment by chocho-1115** [comment]
brew install libtool automake autoconf pkgconf
