### ISSUE TITLE
strange errors

### ISSUE THREAD

**Issue by lqzerogg** [imagemin/imagemin#193]
I got a very strange error recently. I don't know whether or not it's imagemin's error. But I would be very pleased if you could figure out why this happen.
I ran into this trouble through image-webpack-loader, and I have commit a issue at that project. Here is the [link](https://github.com/tcoopman/image-webpack-loader/issues/40).

Here's my errors:
Module build failed: ModuleBuildError: Module build failed: Error: spawn /Users/Zero/projects/livebet-client-code/node_modules/pngquant-bin/vendor/pngquant EAGAIN
    at exports._errnoException (util.js:949:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at DependenciesBlock.onModuleBuildFailed (/Users/Zero/projects/livebet-client-code/node_modules/webpack-core/lib/NormalModuleMixin.js:315:19)
    at nextLoader (/Users/Zero/projects/livebet-client-code/node_modules/webpack-core/lib/NormalModuleMixin.js:270:31)
    at /Users/Zero/projects/livebet-client-code/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at context.callback (/Users/Zero/projects/livebet-client-code/node_modules/webpack-core/lib/NormalModuleMixin.js:148:14)
    at imagemin.buffer.then.catch.err (/Users/Zero/projects/livebet-client-code/node_modules/image-webpack-loader/index.js:42:9)
    at process._tickCallback (internal/process/next_tick.js:103:7)

ERROR in ./feSRC/img/flags/GR_18X12@2x.png
    Module build failed: Error: spawn /Users/Zero/projects/livebet-client-code/node_modules/pngquant-bin/vendor/pngquant EAGAIN
        at exports._errnoException (util.js:949:11)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
        at onErrorNT (internal/child_process.js:348:16)
        at _combinedTickCallback (internal/process/next_tick.js:74:11)
        at process._tickCallback (internal/process/next_tick.js:98:9)
     @ ./~/css-loader?sourceMap&localIdentName=[path][name]---[local]---[hash:base64:5]!./~/postcss-loader!./feSRC/view/pages/profile/index.scss 6:13630-13675

**Comment by tonghuashuo** [comment]
I'm experiencing similar problems with `gulp-imagemin`. At first I thought maybe the image format wasn't right. Tried over 10 different images with different formats. All failed.

here's my gulp task definition:
```
gulp.task('compress-images', function () {
    gulp.src('src/img/*')
        .pipe(imagemin())
        .pipe(gulp.dest('dist/img'))
});
```

here's the output when I run the task alone. (not quite useful for solving it myself so i turned into you)
```
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: spawn /Users/washington/Sites/me/test/node_modules/jpegtran-bin/vendor/jpegtran ENOENT
    at exports._errnoException (util.js:1008:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Please help me.

**Comment by lcw5945** [comment]
I got same error

**Comment by lcw5945** [comment]
I got same error , in Linux 
``` js
Unhandled rejection Error: spawn /home/work-develop/git/starway-js-web/node_modules/gulp-imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/vendor/gifsicle ENOENT
    at exports._errnoException (util.js:907:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
```

**Comment by kevva** [comment]
`ENOENT` means that it can't find the binary. `jpegtran` has most likely failed to install.

**Comment by lqzerogg** [comment]
@kevva , it seems not because of what you said. When I cut down the number of images being processed, this error disappears! Anyway, I have figured out a way to avoid this problem. [link](https://github.com/tcoopman/image-webpack-loader/issues/40)
