### ISSUE TITLE
npm install imagemin error because of jpegtran-bin

### ISSUE THREAD

**Issue by managombo** [imagemin/imagemin#195]
Hello,
I am o windows 10 system and I tried to install the gulp-imagemin package but I have an issue when installing it. It gives me the output below:

```
npm install gulp-imagemin --save-dev
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!

> jpegtran-bin@3.1.0 postinstall C:\Users\..\node_modules\jpegtran-bin
> node lib/install.js

internal/child_process.js:298
    throw errnoException(err, 'spawn');
    ^

Error: spawn EPERM
    at exports._errnoException (util.js:907:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at exports.spawn (child_process.js:362:9)
    at C:\Users\..\node_modules\bin-check\index.js:22:12
    at C:\Users\..\node_modules\executable\index.js:27:4
    at FSReqWrap.oncomplete (fs.js:82:15)
 npm WARN install:jpegtran-bin@3.1.0 jpegtran-bin@3.1.0 postinstall: `node lib/install.js`
npm WARN install:jpegtran-bin@3.1.0 Exit status 1
conFusion@ C:\Users\..\conFusion
`-- gulp-imagemin@3.0.3

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
```

Thank you for helping me resolving this issue.

**Comment by shinnn** [comment]
http://www.catb.org/esr/faqs/smart-questions.html#forum
