### ISSUE TITLE
Getting ENOENT error with gifsicle

### ISSUE THREAD

**Issue by stewx** [imagemin/imagemin#197]
In Ubuntu 14.04, I get the following error when I run imagemin in my Gulp build. Any idea how to resolve this?

Versions:
node 4.5.0
npm 2.15.9
imagemin 5.2.2
imagemin-gifsicle 5.1.0
```
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: spawn /myproject/node_modules/gulp-imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/vendor/gifsicle ENOENT
    at exports._errnoException (util.js:907:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
```

**Comment by shinnn** [comment]
http://www.catb.org/esr/faqs/smart-questions.html#forum https://github.com/imagemin/imagemin-gifsicle/issues/13
