### ISSUE TITLE
imagemin exec throws "TypeError: Cannot read property 'kill' of undefined" ?

### ISSUE THREAD

**Issue by listsssl** [imagemin/imagemin#198]
I'm just getting started with imagemin under gulp control.

I installed gulp-imagemin
```
cd /srv/www/site1
node --version
	v6.4.0
npm -v
	3.10.6
```
following the recommendation at this closed bug
#https://github.com/sindresorhus/gulp-imagemin/issues/173#issuecomment-230737023
```
npm uninstall --save-dev gulp-imagemin
npm cache clean
npm install --save-dev gulp-imagemin
npm ls | grep imagemin
	├─┬ gulp-imagemin@3.0.3
	│ ├─┬ imagemin@5.2.2
	│ ├─┬ imagemin-gifsicle@5.1.0
	│ ├─┬ imagemin-jpegtran@5.0.2
	│ ├─┬ imagemin-optipng@5.2.0
	│ ├─┬ imagemin-svgo@5.2.0
```
my Gulpfile.js is
```
var gulp    = require('gulp');
var imgmin  = require('gulp-imagemin');
var optipng = require('imagemin-optipng');

gulp.task('imgmin', ['pngmin']);

gulp.task('pngmin', function() {
	gulp.src('/srv/www/site1/img/*')
		.pipe(imgmin({
			use: [optipng({optimizationLevel:3})]
		}))
	.pipe(gulp.dest('/srv/www/site1/img/min'));
});
```
When I exec
```
	gulp imgmin
```
it returns
```
[10:40:37] Using gulpfile /srv/www/site1/Gulpfile.js
[10:40:37] Starting 'pngmin'...
[10:40:37] Finished 'pngmin' after 16 ms
[10:40:37] Starting 'imgmin'...
[10:40:37] Finished 'imgmin' after 22 μs

events.js:160
      throw er; // Unhandled 'error' event
      ^
TypeError: Cannot read property 'kill' of undefined
    at module.exports (/srv/www/site1/node_modules/execa/index.js:80:24)
    at fsP.writeFile.then (/srv/www/site1/node_modules/exec-buffer/index.js:31:15)
```
no minimized files are populated in .../min

**Comment by kevva** [comment]
https://github.com/sindresorhus/gulp-imagemin/issues/173

**Comment by listsssl** [comment]
@ kevva

> sindresorhus/gulp-imagemin#173

What does simply pasting a URL mean?

I referenced that bug in my post above, mentioned that I followed its recommendations, and that I *still* see the error?
