### ISSUE TITLE
Error in file + The system cannot find the path specified. under windows 10

### ISSUE THREAD

**Issue by abumalick** [imagemin/imagemin#209]
When runing imagemin-cli I get "The system cannot find the path specified." error on windows 10, cannot make it work.:

```
C:\2016\05>imagemin 01.jpg > test.jpg
Error: Error in file: 01.jpg

The system cannot find the path specified.

    at notFoundError (C:\Users\abdul\AppData\Roaming\npm\node_modules\imagemin-cli\node_modules\cross-spawn\lib\enoent.js:11:11)
    at verifyENOENT (C:\Users\abdul\AppData\Roaming\npm\node_modules\imagemin-cli\node_modules\cross-spawn\lib\enoent.js:46:16)
    at ChildProcess.cp.emit (C:\Users\abdul\AppData\Roaming\npm\node_modules\imagemin-cli\node_modules\cross-spawn\lib\enoent.js:33:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

```
C:\2016\05>imagemin brussels-buildings.jpg --out-dir=im
Error: Error in file: brussels-buildings.jpg

The system cannot find the path specified.

    at notFoundError (C:\Users\abdul\AppData\Roaming\npm\node_modules\imagemin-cli\node_modules\cross-spawn\lib\enoent.js:11:11)
    at verifyENOENT (C:\Users\abdul\AppData\Roaming\npm\node_modules\imagemin-cli\node_modules\cross-spawn\lib\enoent.js:46:16)
    at ChildProcess.cp.emit (C:\Users\abdul\AppData\Roaming\npm\node_modules\imagemin-cli\node_modules\cross-spawn\lib\enoent.js:33:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

```
C:\2016\05>imagemin --version
3.0.0
```

I don't really understand what I am doing wrong. The installation was ok.
Possible duplicate : #199 but I get a different error code ...

**Comment by tonn** [comment]
Have same problem.
Dependencies of imagemin-* plugins was installed incorrect.
In my case it was mozjpeg and pngquant-bin. There was not vendor subfolder with executables.
`npm install --force mozjpeg` solve the problem

**Comment by shinnn** [comment]
Reinstall dependencies.

**Comment by aikar** [comment]
For anyone who runs into this ticket trying to debug this error on why `npm run <script>` doesn't work on Windows for things in node_modules/.bin/ such as gulp, it relates to the fact that npm is using cmd.exe instead of bash for the child.

You can fix this with NPM 5.1.0+ using `npm config set script-shell bash`

**Comment by ph1112** [comment]
删除node_modules
设置 npm install -g cnpm --registry=https://registry.npmmirror.com
在需要压缩的文件夹执行 cnpm i

**Comment by ph1112** [comment]
![image](https://github.com/user-attachments/assets/6e7bc810-71d5-426e-b9be-e6583f808373)
