### ISSUE TITLE
Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by thisconnect** [imagemin/imagemin#211]
Hi, I am using the imagemin.buffer api and run into the following warning, when I try to compress more than 10 images using `Promise.all`. As far as I understand all imagemin plugins use exec-buffer, which uses execa. Possible related: https://github.com/sindresorhus/execa/issues/61

```
(node:41926) Warning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:259:19)
    at EventEmitter.addListener (events.js:275:10)
    at module.exports (node_modules/signal-exit/index.js:41:11)
    at module.exports.err (node_modules/exec-buffer/node_modules/execa/index.js:146:23)
    at fsP.writeFile.then (node_modules/exec-buffer/index.js:35:15)
```

looks like signal-exit uses the same emitter globally, (I believe)
https://github.com/tapjs/signal-exit/blame/master/index.js#L13-L20

My test is something like
```js
const compress = require('./compress.js');
const files = [/* 11 files */]
Promise.all(files.map(file => compress(file)))
.then(() => console.log('woohoo done!'))
.catch(err => t.fail(err))
```

### compress.js

```js
const imagemin = require('imagemin');
const imageminJpegtran = require('imagemin-jpegtran');
const imageminPngquant = require('imagemin-pngquant');
const imageminGifsicle = require('imagemin-gifsicle');
const imageminSVGO = require('imagemin-svgo');

module.exports = buffer => {
  return imagemin.buffer(buffer, {
    plugins: [
      imageminPngquant({
        quality: '10-100'
      }),
      imageminJpegtran({
        progressive: true
      }),
      imageminSVGO(),
      imageminGifsicle({
        // interlaced: false,
        // optimizationLevel: 1,
        // colors:
      })
    ]
  });
}

```

Let me know if I should create a test repo

**Comment by yibuyisheng** [comment]
same problem

**Comment by thisconnect** [comment]
discussion seems to continue here https://github.com/sindresorhus/execa/issues/61

try `process.setMaxListeners(<number>)`  if this is the solution it should be documented "somewhere"

**Comment by shinnn** [comment]
Fixed in https://github.com/tapjs/signal-exit/commit/395ccc8cf3cc119dc98a0d38940dbfaa590af0cd 🎉
