### ISSUE TITLE
error with osx

### ISSUE THREAD

**Issue by acegank** [imagemin/imagemin#222]
my os is macosx 

help me!

gulpfile.js : 

gulp.task('images-opt', function () {
    gulp.src('./images/*.+(jpeg|jpg|png)')
        .pipe(imagemin({
            progressive: true,
            use: [pngquant({quality: '65-80'})]
        }))
        .pipe(gulp.dest('./assets/'));
});

events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: spawn /Users/k/HBuilderProjects/家教/node_modules/.3.2.0@jpegtran-bin/vendor/jpegtran ENOENT
    at exports._errnoException (util.js:873:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)

**Comment by shinnn** [comment]
Reinstall `jpegtran-bin` module correctly.
