### ISSUE TITLE
Command failed: jpegtran

### ISSUE THREAD

**Issue by xaviervalarino** [imagemin/imagemin#236]
I am having some issues trying to optimize jpegs with a globally installed version of `imagemin-cli@3.0.0` on OSX 10.11.6.

Here is the output from my terminal:
```
$ imagemin image.jpg > optimized.jpg

Error: Error in file: image.jpg

Command failed:
/Users/xavier/.npm-global/lib/node_modules/imagemin-cli/node_modules/jpegtran-bin/vendor/jpegtran -copy none -optimize -outfile /var/folders/y_/b8s6h6j132q_bt5hq8vvg8vr0000gn/T/bf75f426-a810-4325-a3c1-8be58bebc140 /var/folders/y_/b8s6h6j132q_bt5hq8vvg8vr0000gn/T/81fc443a-89a2-4043-ae06-e2e67f7224f4

    at Promise.all.then.arr (/Users/xavier/.npm-global/lib/node_modules/imagemin-cli/node_modules/execa/index.js:201:11)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

Installing `jpegtran-bin` makes some complaints about the binary version:
```
$ npm i -g jpegtran-bin

/Users/xavier/.npm-global/bin/jpegtran -> /Users/xavier/.npm-global/lib/node_modules/jpegtran-bin/cli.js

> jpegtran-bin@3.2.0 postinstall /Users/xavier/.npm-global/lib/node_modules/jpegtran-bin
> node lib/install.js

  ⚠ The `/Users/xavier/.npm-global/lib/node_modules/jpegtran-bin/vendor/jpegtran` binary doesn't seem to work correctly
  ⚠ jpegtran pre-build test failed
  ℹ compiling from source
  ✖ Error: touch configure.ac aclocal.m4 configure Makefile.am Makefile.in && ./configure --disable-shared --prefix="/Users/xavier/.npm-global/lib/node_modules/jpegtran-bin/vendor" --bindir="/Users/xavier/.npm-global/lib/node_modules/jpegtran-bin/vendor" && make install
Command failed: ./configure --disable-shared --prefix="/Users/xavier/.npm-global/lib/node_modules/jpegtran-bin/vendor" --bindir="/Users/xavier/.npm-global/lib/node_modules/jpegtran-bin/vendor"
configure: error: installation or configuration problem: assembler cannot create object files.

    at ChildProcess.exithandler (child_process.js:205:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:513:12)
```

But running more or less the same command as `imagemin` seems to work:
```
$ jpegtran -copy none -optimize -outfile optimized.jpg image.jpg ; du -h *.jpg

656K	image.jpg
612K	optimized.jpg
```

**Comment by coder77** [comment]
having the same problem:
`jpegtran-bin@3.2.0 postinstall /var/www/apps/xxx/node_modules/jpegtran-bin > node lib/install.js`
