### ISSUE TITLE
Update to svgo to 5.2.1 from 5.2.0 causes error

### ISSUE THREAD

**Issue by obble80** [imagemin/imagemin#237]
events.js:141
      throw er; // Unhandled 'error' event
      ^
TypeError: this is not a typed array.
    at Function.from (native)
    at /redacted/node_modules/gulp-imagemin/node_modules/imagemin-svgo/index.js:25:19
    at optimizeOnceCallback (/redacted/node_modules/gulp-imagemin/node_modules/imagemin-svgo/node_modules/svgo/lib/svgo.js:44:17)
    at /redacted/node_modules/gulp-imagemin/node_modules/imagemin-svgo/node_modules/svgo/lib/svgo.js:65:9
    at Object.sax.onend (/redacted/node_modules/gulp-imagemin/node_modules/imagemin-svgo/node_modules/svgo/lib/svgo/svg2js.js:156:13)
    at emit (/redacted/node_modules/gulp-imagemin/node_modules/imagemin-svgo/node_modules/svgo/node_modules/sax/lib/sax.js:640:35)
    at end (/redacted/node_modules/gulp-imagemin/node_modules/imagemin-svgo/node_modules/svgo/node_modules/sax/lib/sax.js:683:5)
    at Object.write (/redacted/node_modules/gulp-imagemin/node_modules/imagemin-svgo/node_modules/svgo/node_modules/sax/lib/sax.js:991:14)
    at Object.SAXParser.close (/redacted/node_modules/gulp-imagemin/node_modules/imagemin-svgo/node_modules/svgo/node_modules/sax/lib/sax.js:157:38)
    at module.exports (/redacted/node_modules/gulp-imagemin/node_modules/imagemin-svgo/node_modules/svgo/lib/svgo/svg2js.js:169:28)

**Comment by sngreg** [comment]
I am seeing this same error.

**Comment by mrmmccann-lufthansa** [comment]
I am facing same error.

**Comment by pierre-r** [comment]
I had the same error. I've updated nodejs & npm to the current latest version and it works now 
nodejs : v6.10.1
npm : v4.4.4

**Comment by shinnn** [comment]
Not an issue with this repository.
