### ISSUE TITLE
Errors with npm5/node8

### ISSUE THREAD

**Issue by kud** [imagemin/imagemin#245]
```shell
> fsevents@1.1.1 install /Users/kud/Projects/_contexte/lois-webapp/node_modules/fsevents
> node install

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ '/usr/local/Cellar/node/8.0.0/bin/node',
node-pre-gyp verb cli   '/Users/kud/Projects/_contexte/lois-webapp/node_modules/fsevents/node_modules/.bin/node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build' ]
node-pre-gyp info using node-pre-gyp@https://registry.npmjs.org/node-pre-gyp/-/node-pre-gyp-0.6.33.tgz
node-pre-gyp info using node@8.0.0 | darwin | x64
node-pre-gyp verb command install []
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack TypeError: Cannot read property 'version' of null
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (/Users/kud/Projects/_contexte/lois-webapp/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/versioning.js:270:32)
node-pre-gyp ERR! stack     at install (/Users/kud/Projects/_contexte/lois-webapp/node_modules/fsevents/node_modules/node-pre-gyp/lib/install.js:168:31)
node-pre-gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/Users/kud/Projects/_contexte/lois-webapp/node_modules/fsevents/node_modules/node-pre-gyp/lib/node-pre-gyp.js:50:37)
node-pre-gyp ERR! stack     at run (/Users/kud/Projects/_contexte/lois-webapp/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp:79:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (/Users/kud/Projects/_contexte/lois-webapp/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp:131:1)
node-pre-gyp ERR! stack     at Module._compile (module.js:569:30)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:580:10)
node-pre-gyp ERR! stack     at Module.load (module.js:503:32)
node-pre-gyp ERR! stack     at tryModuleLoad (module.js:466:12)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:458:3)
node-pre-gyp ERR! System Darwin 16.6.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/8.0.0/bin/node" "/Users/kud/Projects/_contexte/lois-webapp/node_modules/fsevents/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/kud/Projects/_contexte/lois-webapp/node_modules/fsevents
node-pre-gyp ERR! node -v v8.0.0
node-pre-gyp ERR! node-pre-gyp -v vhttps://registry.npmjs.org/node-pre-gyp/-/node-pre-gyp-0.6.33.tgz
node-pre-gyp ERR! not ok
Cannot read property 'version' of null

> pngquant-bin@3.1.1 postinstall /Users/kud/Projects/_contexte/lois-webapp/node_modules/pngquant-bin
> node lib/install.js

  ⚠ Response code 404 (Not Found)
  ⚠ pngquant pre-build test failed
  ℹ compiling from source
  ✔ pngquant built successfully

> optipng-bin@3.1.4 postinstall /Users/kud/Projects/_contexte/lois-webapp/node_modules/optipng-bin
> node lib/install.js

  ⚠ Response code 404 (Not Found)
  ⚠ optipng pre-build test failed
  ℹ compiling from source
  ✔ optipng built successfully

> mozjpeg@4.1.1 postinstall /Users/kud/Projects/_contexte/lois-webapp/node_modules/mozjpeg
> node lib/install.js

  ⚠ Response code 404 (Not Found)
  ⚠ mozjpeg pre-build test failed
  ℹ compiling from source
  ✖ Error: autoreconf -fiv && ./configure --disable-shared --prefix="/Users/kud/Projects/_contexte/lois-webapp/node_modules/mozjpeg/vendor" --bindir="/Users/kud/Projects/_contexte/lois-webapp/node_modules/mozjpeg/vendor" --libdir="/Users/kud/Projects/_contexte/lois-webapp/node_modules/mozjpeg/vendor" && make --jobs=4 && make install --jobs=4
Command failed: autoreconf -fiv
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal  --output=aclocal.m4t
Can't exec "aclocal": No such file or directory at /usr/local/Cellar/autoconf/2.69/share/autoconf/Autom4te/FileUtils.pm line 326.
autoreconf: failed to run aclocal: No such file or directory

    at ChildProcess.exithandler (child_process.js:252:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:887:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)

> gifsicle@3.0.4 postinstall /Users/kud/Projects/_contexte/lois-webapp/node_modules/gifsicle
> node lib/install.js

  ⚠ Response code 404 (Not Found)
  ⚠ gifsicle pre-build test failed
  ℹ compiling from source
  ✖ Error: autoreconf -ivf && ./configure --disable-gifview --disable-gifdiff --prefix="/Users/kud/Projects/_contexte/lois-webapp/node_modules/gifsicle/vendor" --bindir="/Users/kud/Projects/_contexte/lois-webapp/node_modules/gifsicle/vendor" && make install
Command failed: autoreconf -ivf
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal  --output=aclocal.m4t
Can't exec "aclocal": No such file or directory at /usr/local/Cellar/autoconf/2.69/share/autoconf/Autom4te/FileUtils.pm line 326.
autoreconf: failed to run aclocal: No such file or directory

    at ChildProcess.exithandler (child_process.js:252:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:887:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@https://registry.npmjs.org/fsevents/-/fsevents-1.1.1.tgz (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.1 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```

**Comment by kud** [comment]
I come here because `image-webpack-loader` uses `imagemin` but I'm not sure from whom is the problem.

**Comment by kevva** [comment]
It has already been reported over at https://github.com/imagemin/mozjpeg-bin/issues and https://github.com/imagemin/gifsicle-bin/issues/72.

**Comment by kud** [comment]
Thank you!

**Comment by kud** [comment]
However installing automake did not change anything. I'll search a solution. Thank you anyway.

**Comment by shrpne** [comment]
@kevva issues you referenced are not related to node8.

jpegtran-bin, mozjpeg-bin, gifsicle-bin are broken after update to node8. With node6 and node7 everything works fine.

I think you should reopen this. Because seems like, these 3 repos are affected by same error.

**Comment by maifs** [comment]
I am facing the same issue .
what do i need to fix it ?
Kindly guide. thank you.

https://stackoverflow.com/questions/44462901/how-to-install-latest-angular-cli-using-visual-studio-2017-node-js-interactive-w
