### ISSUE TITLE
Task failing, notFoundError node_modules\cross-spawn\lib\enoent.js:11:11

### ISSUE THREAD

**Issue by drgs100** [imagemin/imagemin#249]
```
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: The system cannot find the path specified.

    at notFoundError (\tasks\node_modules\cross-spawn\lib\enoent.js:11:11)
    at verifyENOENT (\tasks\node_modules\cross-spawn\lib\enoent.js:46:16)
    at ChildProcess.cp.emit (\tasks\node_modules\cross-spawn\lib\enoent.js:33:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```
**Enviroment details**
npm 3.10.10
node 6.11.2
Windows 10 Enterprise (64-bit)
gulp 3.9.1
gulp-imagemin 3.3.0

Issue also seen on branch: https://github.com/sindresorhus/gulp-imagemin.

**Comment by Guilherme-Chinaglia** [comment]
I'm with this same error too.

**Comment by vivayue** [comment]
I'm with this same error too.
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: ϵͳ�Ҳ���ָ����·����

    at notFoundError (F:\测试_project\gulp任务处理\node_modules\.5.1.0@cross-spawn\lib\enoent.js:11:11)
    at verifyENOENT (F:\测试_project\gulp任务处理\node_modules\.5.1.0@cross-spawn\lib\enoent.js:46:16)
    at ChildProcess.cp.emit (F:\测试_project\gulp任务处理\node_modules\.5.1.0@cross-spawn\lib\enoent.js:33:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
**Enviroment details**
npm: 4.4.2
node: 6.9.3
windows 10
gulp: 3.9.1

**Comment by crick64** [comment]
Have you try to install npm inside the gulp-imagemin directory:

```
cd path\to\the\project\node_modules\gulp-imagemin
npm i
```
This issue is solved at [https://github.com/sindresorhus/gulp-imagemin/issues/245#issuecomment-391177111](url)

**Comment by NgocAnPham** [comment]
> Have you try to install npm inside the gulp-imagemin directory:
> 
> ```
> cd path\to\the\project\node_modules\gulp-imagemin
> npm i
> ```
> This issue is solved at [https://github.com/sindresorhus/gulp-imagemin/issues/245#issuecomment-391177111](url)
It not work for me

**Comment by zhangming8691** [comment]
> Have you try to install npm inside the gulp-imagemin directory:
> 
> ```
> cd path\to\the\project\node_modules\gulp-imagemin
> npm i
> ```
> 
> This issue is solved at [https://github.com/sindresorhus/gulp-imagemin/issues/245#issuecomment-391177111](url)

Thank you very much.
