### ISSUE TITLE
Getting permission denied errors when i try to install this module globally with SUDO

### ISSUE THREAD

**Issue by alexbudin** [imagemin/imagemin#256]
This is the error i get:

```
sudo npm install -g imagemin-cli
Password:
/usr/local/bin/imagemin -> /usr/local/lib/node_modules/imagemin-cli/cli.js

> gifsicle@3.0.4 postinstall /usr/local/lib/node_modules/imagemin-cli/node_modules/gifsicle
> node lib/install.js

  ⚠ EACCES: permission denied, mkdir '/usr/local/lib/node_modules/imagemin-cli/node_modules/gifsicle/vendor'
  ⚠ gifsicle pre-build test failed
  ℹ compiling from source
/usr/local/lib/node_modules/imagemin-cli/node_modules/onetime/index.js:15
				throw new Error(fnName + ' can only be called once.');
				^

Error: callback() can only be called once.
    at onetime (/usr/local/lib/node_modules/imagemin-cli/node_modules/onetime/index.js:15:11)
    at /usr/local/lib/node_modules/imagemin-cli/node_modules/download/index.js:156:5
    at ConcatStream.<anonymous> (/usr/local/lib/node_modules/imagemin-cli/node_modules/concat-stream/index.js:36:43)
    at emitNone (events.js:110:20)
    at ConcatStream.emit (events.js:207:7)
    at finishMaybe (/usr/local/lib/node_modules/imagemin-cli/node_modules/readable-stream/lib/_stream_writable.js:607:14)
    at endWritable (/usr/local/lib/node_modules/imagemin-cli/node_modules/readable-stream/lib/_stream_writable.js:615:3)
    at ConcatStream.Writable.end (/usr/local/lib/node_modules/imagemin-cli/node_modules/readable-stream/lib/_stream_writable.js:571:41)
    at DuplexWrapper.onend (/usr/local/lib/node_modules/imagemin-cli/node_modules/readable-stream/lib/_stream_readable.js:570:10)
    at Object.onceWrapper (events.js:314:30)

> jpegtran-bin@3.2.0 postinstall /usr/local/lib/node_modules/imagemin-cli/node_modules/jpegtran-bin
> node lib/install.js

  ⚠ EACCES: permission denied, mkdir '/usr/local/lib/node_modules/imagemin-cli/node_modules/jpegtran-bin/vendor'
  ⚠ jpegtran pre-build test failed
  ℹ compiling from source
/usr/local/lib/node_modules/imagemin-cli/node_modules/onetime/index.js:15
				throw new Error(fnName + ' can only be called once.');
				^

Error: callback() can only be called once.
    at onetime (/usr/local/lib/node_modules/imagemin-cli/node_modules/onetime/index.js:15:11)
    at /usr/local/lib/node_modules/imagemin-cli/node_modules/download/index.js:156:5
    at ConcatStream.<anonymous> (/usr/local/lib/node_modules/imagemin-cli/node_modules/concat-stream/index.js:36:43)
    at emitNone (events.js:110:20)
    at ConcatStream.emit (events.js:207:7)
    at finishMaybe (/usr/local/lib/node_modules/imagemin-cli/node_modules/readable-stream/lib/_stream_writable.js:607:14)
    at endWritable (/usr/local/lib/node_modules/imagemin-cli/node_modules/readable-stream/lib/_stream_writable.js:615:3)
    at ConcatStream.Writable.end (/usr/local/lib/node_modules/imagemin-cli/node_modules/readable-stream/lib/_stream_writable.js:571:41)
    at DuplexWrapper.onend (/usr/local/lib/node_modules/imagemin-cli/node_modules/readable-stream/lib/_stream_readable.js:570:10)
    at Object.onceWrapper (events.js:314:30)

> optipng-bin@3.1.4 postinstall /usr/local/lib/node_modules/imagemin-cli/node_modules/optipng-bin
> node lib/install.js

  ⚠ EACCES: permission denied, mkdir '/usr/local/lib/node_modules/imagemin-cli/node_modules/optipng-bin/vendor'
  ⚠ optipng pre-build test failed
  ℹ compiling from source
/usr/local/lib/node_modules/imagemin-cli/node_modules/onetime/index.js:15
				throw new Error(fnName + ' can only be called once.');
				^

Error: callback() can only be called once.
    at onetime (/usr/local/lib/node_modules/imagemin-cli/node_modules/onetime/index.js:15:11)
    at /usr/local/lib/node_modules/imagemin-cli/node_modules/download/index.js:156:5
    at ConcatStream.<anonymous> (/usr/local/lib/node_modules/imagemin-cli/node_modules/concat-stream/index.js:36:43)
    at emitNone (events.js:110:20)
    at ConcatStream.emit (events.js:207:7)
    at finishMaybe (/usr/local/lib/node_modules/imagemin-cli/node_modules/readable-stream/lib/_stream_writable.js:607:14)
    at endWritable (/usr/local/lib/node_modules/imagemin-cli/node_modules/readable-stream/lib/_stream_writable.js:615:3)
    at ConcatStream.Writable.end (/usr/local/lib/node_modules/imagemin-cli/node_modules/readable-stream/lib/_stream_writable.js:571:41)
    at DuplexWrapper.onend (/usr/local/lib/node_modules/imagemin-cli/node_modules/readable-stream/lib/_stream_readable.js:570:10)
    at Object.onceWrapper (events.js:314:30)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: gifsicle@3.0.4 (node_modules/imagemin-cli/node_modules/gifsicle):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: gifsicle@3.0.4 postinstall: `node lib/install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: jpegtran-bin@3.2.0 (node_modules/imagemin-cli/node_modules/jpegtran-bin):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: jpegtran-bin@3.2.0 postinstall: `node lib/install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: optipng-bin@3.1.4 (node_modules/imagemin-cli/node_modules/optipng-bin):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: optipng-bin@3.1.4 postinstall: `node lib/install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ imagemin-cli@3.0.0
added 358 packages in 10.528s
```

**Comment by alexbudin** [comment]
Can anyone help with this? Has anyone had this problem?

**Comment by raoulh** [comment]
Had the same.

This did the trick:
`sudo npm install -g imagemin-cli --unsafe-perm=true --allow-root`

**Comment by sindresorhus** [comment]
You shouldn't use `sudo`. Fix your permissions or change the global install directory to a different location.

**Comment by toanld** [comment]
npm install -g imagemin-cli --unsafe-perm=true --allow-root
