### ISSUE TITLE
webpack-dev-server' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by LanreOlanipekun** [imagemin/imagemin#258]
i have been trying to work on the vue-cli and run the npm run dev but i keep getting this error

events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: spawn webpack-dev-server ENOENT
    at notFoundError (C:\Users\Lanre\AppData\Roaming\npm\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:11:11)
    at verifyENOENT (C:\Users\Lanre\AppData\Roaming\npm\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:46:16)
    at ChildProcess.cp.emit (C:\Users\Lanre\AppData\Roaming\npm\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:3
3:19) at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vuedemoapp@1.0.0 dev: `cross-env NODE_ENV=development webpack-dev-server --open --hot`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vuedemoapp@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Please Help

**Comment by sindresorhus** [comment]
Doesn't seem related to this project.
