### ISSUE TITLE
Unknown plugin: gifsicle

### ISSUE THREAD

**Issue by expert101** [imagemin/imagemin#270]
In mac:

$ sudo npm install -g imagemin-cli
no errors reported

$ imagemin img/* -o dist/img/
Throws an error
> Unknown plugin: gifsicle
> Did you forgot to install the plugin?
> You can install it with:  $ npm install -g imagemin-gifsicle

So I tried to install the plugin but ran into problems there too!

$ sudo npm install -g imagemin-gifsicle
Throws this error
> > gifsicle@3.0.4 postinstall /usr/local/lib/node_modules/imagemin-gifsicle/node_modules/gifsicle
> > node lib/install.js
> 
>   ⚠ EACCES: permission denied, mkdir '/usr/local/lib/node_modules/imagemin-gifsicle/node_modules/gifsicle/vendor'
>   ⚠ gifsicle pre-build test failed
>   ℹ compiling from source
> /usr/local/lib/node_modules/imagemin-gifsicle/node_modules/onetime/index.js:15
> 				throw new Error(fnName + ' can only be called once.');
> 				^
> 
> Error: callback() can only be called once.
>     at onetime (/usr/local/lib/node_modules/imagemin-gifsicle/node_modules/onetime/index.js:15:11)
>     at /usr/local/lib/node_modules/imagemin-gifsicle/node_modules/download/index.js:156:5
>     at ConcatStream.<anonymous> (/usr/local/lib/node_modules/imagemin-gifsicle/node_modules/concat-stream/index.js:36:43)
>     at emitNone (events.js:111:20)
>     at ConcatStream.emit (events.js:208:7)
>     at finishMaybe (/usr/local/lib/node_modules/imagemin-gifsicle/node_modules/readable-stream/lib/_stream_writable.js:607:14)
>     at endWritable (/usr/local/lib/node_modules/imagemin-gifsicle/node_modules/readable-stream/lib/_stream_writable.js:615:3)
>     at ConcatStream.Writable.end (/usr/local/lib/node_modules/imagemin-gifsicle/node_modules/readable-stream/lib/_stream_writable.js:571:41)
>     at DuplexWrapper.onend (/usr/local/lib/node_modules/imagemin-gifsicle/node_modules/readable-stream/lib/_stream_readable.js:570:10)
>     at Object.onceWrapper (events.js:313:30)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! gifsicle@3.0.4 postinstall: `node lib/install.js`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the gifsicle@3.0.4 postinstall script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/xxxxx/.npm/_logs/2017-12-17T17_54_35_837Z-debug.log

**Comment by expert101** [comment]
The work around is
$ sudo npm install -g imagemin-cli --unsafe-perm=true --allow-root

**Comment by jsntcxy66** [comment]
I tried `npm install` and it works.

**Comment by ShivamChawla01** [comment]
@expert101 ,same issue here but I still can't build the dist folder

**Comment by tomasmatulis0** [comment]
`yarn add -D imagemin-gifsicle` helped for me
