### ISSUE TITLE
node imagemin write epipe error!

### ISSUE THREAD

**Issue by HadiAbbasi** [imagemin/imagemin#281]
Hi there...
when I tried to minify some images on my centos, I encountered   write EPIPE error!
I think it is on temp witing!
```
{ success: false,
  error:
   { Error: Error in file: /tmp/11846-22021-160x02l.2d89drhpvi

   write EPIPE
       at exports._errnoException (util.js:1020:11)
       at WriteWrap.afterWrite (net.js:800:14)
     code: 'EPIPE',
     errno: 'EPIPE',
     syscall: 'write',
     killed: false,
     stdout: <Buffer >,
     stderr: <Buffer 2f 68 6f 6d 65 2f 57 43 44 4e 2d 4e 6f 64 65 4a 53 2d 48 65 6c 70 65 72 2f 6e 6f 64 65 5f 6d 6f 64 75 6c 65 73 2f 6d 6f 7a 6a 70 65 67 2f 76 65 6e 64 ... >,
     failed: true,
     signal: null,
     cmd: '/home/WCDN-NodeJS-Helper/node_modules/mozjpeg/vendor/cjpeg',
     timedOut: false } }

```
so I want to solve it! also I have tried this command but still it is not working!
`chmod -R 1777 /tmp/`

please give me the solution!
thanks a lot...

**Comment by mattcheah** [comment]
I have the same issue here. Hoping someone can tell me what might be going on: 

```
{ Error: Error in file: /home/me/public_html/myfile.jpg

write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:844:14)
  errno: 'EPIPE',
  code: 'EPIPE',
  syscall: 'write',
  killed: false,
  stdout: <Buffer >,
  stderr: <Buffer 2f 68 6f 6d 65 2f 62 65 73 74 61 74 74 6f 2f 6e 6f 64 65 5f 6d 6f 64 75 6c 65 73 2f 6d 6f 7a 6a 70 65 67 2f 76 65 6e 64 6f 72 2f 63 6a 70 65 67 3a 20 ... >,
  failed: true,
  signal: null,
  cmd: '/home/me/node_modules/mozjpeg/vendor/cjpeg -quality 70',
  timedOut: false }
```

Note - this doesn't happen to all images, but if I re-run the script, this file will continually have problems.
