### ISSUE TITLE
Error while installing npm plugin

### ISSUE THREAD

**Issue by ebitauld** [imagemin/imagemin#283]
The installation of the dependencies (gifsicle, jpegtran-bin,optipng-bin) fails.
The problem appeared few days ago.

`>npm` install --save-dev gulp-image-optimization`
`path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received { url: 'https://raw.github.com/imagemin/optipng-bin/v0.3.11/vendor/win/optipng.exe',
  name: 'optipng.exe',
  os: 'win32' }
    at assertPath (path.js:7:11)
    at Object.basename (path.js:799:5)
    at D:\WWW\MyProject\node_modules\image-min\node_modules\download\index.js:35:43
    at each (D:\WWW\MyProject\node_modules\image-min\node_modules\each-async\each-async.js:63:4)
    at module.exports (D:\WWW\MyProject\node_modules\image-min\node_modules\download\index.js:33:5)
    at D:\WWW\MyProject\node_modules\image-min\node_modules\bin-wrapper\index.js:108:20
    at D:\WWW\MyProject\node_modules\image-min\node_modules\bin-wrapper\index.js:141:24
    at D:\WWW\MyProject\node_modules\image-min\node_modules\bin-check\index.js:30:20
    at D:\WWW\MyProject\node_modules\image-min\node_modules\executable\index.js:39:20
    at FSReqWrap.oncomplete (fs.js:123:15)
`
When I try other gulp plugin based on the same compressor tool (optipng.exe ...) I get this error:
`> optipng-bin@4.0.0 postinstall D:\WWW\Covoitaubin\node_modules\optipng-bin
> node lib/install.js

  ‼ self signed certificate in certificate chain
  ‼ optipng pre-build test failed
  i compiling from source
  **× RequestError: self signed certificate in certificate chain**
    at ClientRequest.<anonymous> (D:\WWW\Covoitaubin\node_modules\got\index.js:74:21)
    at ClientRequest.g (events.js:292:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1277:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
`
I suppose a problem with the hosting of optipng tool

**Comment by jamesray** [comment]
https://raw.githubusercontent.com/imagemin/gifsicle-bin/5.1.0/vendor/

the url above is giving a 404 error, triggering a build from source, on a pure node image for example this would be impossible! @ebitauld you'll need something to build the image from source, that ended up being my solution.
