### ISSUE TITLE
Plugins throwing exceptions on AWS Lambda

### ISSUE THREAD

**Issue by rcvink** [imagemin/imagemin#297]
I've built a simple express api that minifies images using imagemin with the following plugins:

- gifsicle
- jpegtran
- optipng
- zopfli

This API works correctly when host locally. It compresses images and sends them back to the client.

To deploy to AWS Lambda, first I ran `npm install` locally, then compress the entire project (including node_modules) in a .zip and upload to Lambda manually. My Lambda function is running Node 8.

I have since tested all other aspects of the Lambda and the AWS API Gateway and they are functioning well. When sending images for compression to the deployed URL (which passes onto the Lambda function), the following errors appear in my CloudWatch logs:
```
2018-10-05T16:38:28.121Z	158daaf2-c8bd-11e8-bfb3-3d6074a8db11	(node:1) UnhandledPromiseRejectionWarning: Error: spawn /var/task/node_modules/optipng-bin/vendor/optipng ENOENT
at _errnoException (util.js:1022:11)
at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
at onErrorNT (internal/child_process.js:372:16)
at _combinedTickCallback (internal/process/next_tick.js:138:11)
at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

The same error appears for the other plugins depending on which is POSTed to the endpoint.

From reading other issues on this repo and the repos for the respective plugins, it seems this issue might relate to the post-install script that is run after `npm install` for each plugin. The post-install scripts ran successfully on my machine but I'm concerned that this isn't representative of the machine my Lambda function is running on. 

Unfortunately I don't see a way to run `npm rebuild` or even `npm install` directly on the Lambda machine. Has anyone had this situation before, and if so what did you do?

**Comment by jagnarock** [comment]
In case somebody is still struggling and the command does not work, there is also another solution, which worked well for me.
Build up the node.js project, ad your package.json with your dependencies and add a buildspec.yml file to your project with following content: 

```
version: 0.2

phases:
  install:
    runtime-versions:
        php: 7.3
  build:
    commands:
      - php --version
      - npm install

artifacts:
  files:
    - '**/*'
```

This file you will need for AWS CodeBuild. Then create a zip package but don't include the node_modules folder. Upload this one to S3, create a new CodeBuild project, go throught the settings - as operating system you need to choose Ubuntu. When building the project, CodeBuild runs the npm install command as specified in the buildspec.yml, will install the needed node_modules and the plugins are compilated for the right environment (AWS Linux). CodeBuild uploads the files back to S3 and in your lambda project you can specify upload from S3 by copying the url from the uploaded zip package by CodeBuild.

**Comment by mreinstein** [comment]
I'm glad you found a solution that works for you, but I don't want to include a whole other service, just to get my dependencies to build correctly  on lambda. The correct solution is to actually fix the modules that don't build correctly.  see https://github.com/imagemin/pngquant-bin/pull/102 and https://github.com/imagemin/gifsicle-bin/pull/106 as examples of what should be done to fix these problems upstream.

**Comment by valentinbdv** [comment]
+1

**Comment by valentinbdv** [comment]
> ```shell
> rm -rf node_modules
> npm install --arch=x64 --platform=linux --target=8.10.0 aws-sdk imagemin imagemin-gifsicle imagemin-jpegtran imagemin-optipng imagemin-zopfli
> ```

This solution didn't work for me unfortunately, even if I install all my package using platform=linux option. Any idea ?

**Comment by tkohout** [comment]
Same here:

```
rm -rf node_modules
npm install --arch=x64 --platform=linux
```

still installs the macosx binaries

As a temporary workaround (for pngquant in my case):

Download the linux binary to the root of lambda: https://github.com/imagemin/pngquant-bin/tree/0cd3a9e21e0e55a4b89e5c8ed214ec443667a0e9/vendor/linux/x64

Add postinstall script to package.json:

```
"scripts": {
    "postinstall": "cp pngquant node_modules/pngquant-bin/vendor/pngquant && chmod u+x node_modules/pngquant-bin/vendor/pngquant"
  },
```

**Comment by Dudeful** [comment]
I just had a similar issue yesterday, on AWS Lambda. In case someone is also facing it, **and** the development environment is Windows, then I believe this is the solution for you. _(note that here in my example I'm using Serverless Framework for building and deploying, however, the principle should work regardless of the use of Serverless)_

I tried a few different solutions, but the easiest and fastest solution was to install the [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10) and run Serverless Deploy from the Ubuntu terminal on windows.

The issue is that some packages are OS-dependent, meaning that the same package installed on different OSs are going to produce different installations. Therefore your locally build/run works fine because you **installed** the packages on Windows environment and you are **running** the packages code on Windows environment, however, when you deploy to AWS it is now running on Amazon Linux and your packages that are OS-dependant _(like mozjpeg, jpegtran, etc)_ are going to fail during the run. So your best shot is to just install the packages, build **and** deploy your project from a Linux environment _(not sure if all Linux distros fit in this statement, but Ubuntu certainly does)_. 

**Here's the timeline for what I did:**

> 1. Install and enable the WSL with Ubuntu _(no big deal at all, 10min top, just follow [Microsofts doc](https://docs.microsoft.com/en-us/windows/wsl/install-win10))_
> 2. Open the Ubuntu terminal **as an administrator** _(if you don't run as administrator it won't allow you to properly run "npm install" in the next steps)_
> 3. Make sure everything is updated, just run _"apt install upgrade"_
> 4. Create a folder by running "mkdir _your-folder-name_" _(or just cd directly into your project's original folder, you can do it by Shift+RightClick on the given folder and choosing "Open Linux Shell Here". I preferred to separate it to avoid messing with my original stuff)_
> 5. Get into the newly created folder by running "cd _your-folder-name_"
> 6. Clone your repository into that folder **or** just copy/paste it manually _(to open your current folder from Ubuntu terminal on Windows just run "explorer.exe .")_
> 7. Run the good and old _"npm install"_ from the Ubuntu terminal
> 8. Now here's a pitfall, if you have your AWS KEYS/SECRETS on your **.env** file, and you set your serverless.yml file to use the environment variables from the .env file, the next step will fail if you don't have the .env file in place _(and you will only see the real error on CloudWatch because the console logged error in the browser will be a CORS error)_
> 9. Run _"Serverless Deploy"_ to deploy your project

That's it. 
Took me around 20min to perform this solution while the others, even though some being effective _(like CodeBuild)_, were more confusing therefore more time-consuming.

**Comment by Dudeful** [comment]
In case someone is having this issue, check it out here #363
