### ISSUE TITLE
Expected `cwd` to be of type `string` but received type `undefined`

### ISSUE THREAD

**Issue by GozuPro** [imagemin/imagemin#311]
Hi guys, 

I'm trying to use imagemin to optimize JPG and PNG from a src folder to a dist folder. For some reason, my simple script doesn't work: `imagemin 01.jpg > 01.jpg`

This is the error I'm getting: 
```
TypeError: Expected `cwd` to be of type `string` but received type `undefined`
    at module.exports (/Users/.../node_modules/dir-glob/index.js:48:25)
    at globDirs (/Users/.../node_modules/globby/index.js:58:9)
    at getPattern (/Users/.../node_modules/globby/index.js:61:64)
    at Promise.all.globTasks.map.task (/Users/.../node_modules/globby/index.js:72:69)
    at Array.map (<anonymous>)
    at module.exports (/Users/.../node_modules/globby/index.js:72:41)
    at module.exports (/Users/.../node_modules/imagemin/index.js:56:9)
    at run (/Users/.../node_modules/imagemin-cli/cli.js:75:2)
    at Object.<anonymous> (/Users/.../node_modules/imagemin-cli/cli.js:107:2)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
```

`npm ls -g imagemin imagemin-cli imagemin-pngquant ` gives the following: 

/Users/ugo.leprudhomme/.nvm/versions/node/v10.8.0/lib
├── imagemin@6.1.0 
├─┬ imagemin-cli@4.0.0 
│ └── imagemin@6.1.0 

I'm using a MacBook Pro with node 8.7.0 without success and I tried with 10.8.0. 
Please let me know if that makes sense to you, any help is appreciated. 

Thanks

**Comment by DonghyukJacobJang** [comment]
I am having the same issue and have a solution.

**`globby` version 8.0.1 needs to upgrade to v9.0.0**

**Comment by GozuPro** [comment]
Indeed @DonghyukJacobJang. I found that yesterday. Thanks for posting it to the rest of the community :)

**Comment by DonghyukJacobJang** [comment]
@GozuPro No worries. If it is urgent, then you may probably want to fork this repo and update it on yours. And, use your own version until they publish a new version with the change.

**Comment by bizmate** [comment]
Was a PR created for this? This is a blocking issue as far as i can see
