### ISSUE TITLE
some error occured

### ISSUE THREAD

**Issue by kebenxiaoming** [imagemin/imagemin#331]
systerm：CENTOS 7

node version: v10.16.3

exception:
/usr/lib/node_modules/imagemin-cli/cli.js:61
const run = async (input, {outDir, plugin = DEFAULT_PLUGINS} = {}) => {
                  ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)

**Comment by kebenxiaoming** [comment]
maybe this version can't support node 10
