### ISSUE TITLE
 Error while trying to minify images

### ISSUE THREAD

**Issue by bogdan-dubyk** [imagemin/imagemin#335]
**npm version: 6.4.1
gulp version: 3.9.1
gulp-imagemin version: 4.1.0**

I'm running all the code under the custom alpine docker container with preinstalled node and I'm getting the error like 
```
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: write callback called multiple times
    at DestroyableTransform.afterTransform (/var/www/vhosts/devgenix/node_modules/readable-stream/lib/_stream_transform.js:84:31)
    at EventEmitter.signals.on.err (/var/www/vhosts/devgenix/node_modules/gulp-cache/lib/index.js:451:7)
    at EventEmitter.emit (events.js:182:13)
    at DestroyableTransform.onError (/var/www/vhosts/devgenix/node_modules/gulp-cache/lib/index.js:288:15)
    at Object.onceWrapper (events.js:273:13)
    at DestroyableTransform.emit (events.js:187:15)
    at Immediate.<anonymous> (/var/www/vhosts/devgenix/node_modules/through2-concurrent/through2-concurrent.js:37:14)
    at runCallback (timers.js:706:11)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
Emitted 'error' event at:
    at DestroyableTransform.onerror (/var/www/vhosts/devgenix/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:558:12)
    at DestroyableTransform.emit (events.js:182:13)
    at DestroyableTransform.afterTransform (/var/www/vhosts/devgenix/node_modules/readable-stream/lib/_stream_transform.js:84:17)
    at EventEmitter.signals.on.err (/var/www/vhosts/devgenix/node_modules/gulp-cache/lib/index.js:451:7)
    [... lines matching original stack trace ...]
    at runCallback (timers.js:706:11)

```

my gulp task looks like:
```
gulp.task('images', () => {
  return gulp.src('assets/images/**/*')
      .pipe($.cache($.imagemin()))
    .pipe(gulp.dest('public/build/images'));
});
```

**Comment by bogdan-dubyk** [comment]
I solve the issue by adding `libjpeg-turbo libjpeg-turbo-dev libpng libpng-dev automake` dependencies to my docker file
