### ISSUE TITLE
imagemin-cli Example command doesn't work

### ISSUE THREAD

**Issue by sebastiantf** [imagemin/imagemin#340]
`$ imagemin --plugin.webp.quality=95 --plugin.webp.preset=icon foo.png > foo-icon.webp`

This example specified in the docs doesn't seem to work.

It produces the following error:

```
Unknown plugin: [object Object]

Did you forget to install the plugin?
You can install it with:

  $ npm install -g imagemin-[object Object]
```

**Comment by mattez** [comment]
You should may be install [**imagemin-webp** plugin ](https://github.com/imagemin/imagemin-webp)
Related issue is https://github.com/imagemin/imagemin/issues/260

**Comment by WangHansen** [comment]
I have a similar one:
`$ imagemin p12.png --plugin.pngquant.quality={0.1,0.2} > ./images/p12.png`

I got:
```bash
ArgumentError: (array `options.quality`) Expected `t` to be of type `number` but received type `string`
```

I believe it has something to do with `imagemin-pngquant`

**Comment by br4nnigan** [comment]
> 
> 
> I have a similar one:
> `$ imagemin p12.png --plugin.pngquant.quality={0.1,0.2} > ./images/p12.png`
> 
> I got:
> 
> ```shell
> ArgumentError: (array `options.quality`) Expected `t` to be of type `number` but received type `string`
> ```


Wow you actually got that far? I got:

    > imagemin test.png --plugin.pngquant.quality={0.1,0.2} > test_opt.png
    Unknown plugin: pngquant

And after installing the plugin I got this: 

`ArgumentError: Expected 'options.quality' to be of type 'array' but received type 'string'`

Don't you love it when the most basic shit from the example already fails?

**Comment by cherryleafroad** [comment]
I got this too
`imagemin 1.png --plugin.pngquant.quality={0.1,0.2} > 1-test.png`

```
ArgumentError: Expected `options.quality` to be of type `array` but received type `string`
    at u (...\nodejs\node_modules\imagemin-pngquant\node_modules\ow\dist\source\index.js:1:12174)
    at ...\nodejs\node_modules\imagemin-pngquant\index.js:35:3
    at ...\nodejs\node_modules\imagemin-cli\node_modules\p-pipe\index.js:12:25
    at handleFile (...\nodejs\node_modules\imagemin-cli\node_modules\imagemin\index.js:21:54)
    at async ...\nodejs\node_modules\imagemin-cli\node_modules\imagemin\index.js:54:13
    at async Promise.all (index 0)
    at async run (...\nodejs\node_modules\imagemin-cli\cli.js:90:11)
    at async ...\nodejs\node_modules\imagemin-cli\cli.js:122:3
```

**Comment by leesei** [comment]
For ``"...but received type `string`"`` issue, see https://github.com/imagemin/imagemin-cli/pull/28
