### ISSUE TITLE
npm imagemin-cli v5.10 Error: Error! 'undefined' is not an integer imagemin-webp RESIZE

### ISSUE THREAD

**Issue by jhauraw** [imagemin/imagemin#346]
All latest npm packages installed on macOS 10.15.3 (19D76)

Resize option throws error:
`imagemin --plugin.webp.quality=75 --plugin.webp.preset=photo --plugin.webp.resize={width:1024,height:0} file.jpg > file.webp`

```shell
Error: Error! 'undefined' is not an integer.

    at /usr/local/lib/node_modules/imagemin-webp/node_modules/execa/index.js:231:11
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /usr/local/lib/node_modules/imagemin-cli/node_modules/p-pipe/index.js:12:19
    at async handleFile (/usr/local/lib/node_modules/imagemin-cli/node_modules/imagemin/index.js:21:9)
    at async /usr/local/lib/node_modules/imagemin-cli/node_modules/imagemin/index.js:54:13
    at async Promise.all (index 0)
    at async run (/usr/local/lib/node_modules/imagemin-cli/cli.js:90:11)
    at async /usr/local/lib/node_modules/imagemin-cli/cli.js:122:3
```

**Comment by leesei** [comment]
Try

```sh
imagemin --plugin.webp.quality=75 --plugin.webp.preset=photo --plugin.webp.resize.width=1024 --plugin.webp.resize.height=0 file.jpg > file.webp
```
