### ISSUE TITLE
minifying GIF - stdout maxBuffer exceeded

### ISSUE THREAD

**Issue by thany** [imagemin/imagemin#360]
When minifying a bunch of gifs from the command line, I get this error at some point:

```
MaxBufferError: stdout maxBuffer exceeded
    at PassThrough.<anonymous> (C:\Users\[snip]\get-stream\index.js:41:19)
    at PassThrough.emit (events.js:327:22)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at PassThrough.Readable.push (_stream_readable.js:212:10)
    at PassThrough.Transform.push (_stream_transform.js:152:32)
    at PassThrough.afterTransform (_stream_transform.js:96:10)
    at PassThrough._transform (_stream_passthrough.js:46:3)
    at PassThrough.Transform._read (_stream_transform.js:191:10)
    at PassThrough.Transform._write (_stream_transform.js:179:12)
```

What's also not great about this, is that all other gifsicle processes are nuked as well when this happens. It might be useful to know, the biggest gif in the collection I'm minifying, is about 33MB. I'm not sure if that's the one it fails on. I don't know which one is causing this crash.

I'm on Node.js 12.18 and imagemin-cli 6.0.0.

*Edit: it appears to crash even on files that are less than 10MB*

**Comment by ExillustX** [comment]
I'm having the same issue.

**Comment by MatheusR42** [comment]
Same here

**Comment by Mr-Thunder** [comment]
I too am having the same issue 
`(node:16700) UnhandledPromiseRejectionWarning: MaxBufferError: stdout maxBuffer exceeded`

node 14.5 and gulp

**Comment by cyberjam** [comment]
Same here

**Comment by cyberjam** [comment]
I solved it this way.

`YOUR_PROJECT/node_modules/imagemin-gifsicle/index.js`

- Before
```
        const {stdout} = await execa(gifsicle, args, {
		encoding: null,
		input,
	});
```

- After
```
        const {stdout} = await execa(gifsicle, args, {
		encoding: null,
                maxBuffer: Number.POSITIVE_INFINITY,
		input,
	});
```

If you want to keep the changes, you can use `patch-package`.
