### ISSUE TITLE
Not usable on Debian 10

### ISSUE THREAD

**Issue by altcointrading** [imagemin/imagemin#379]
node 8 (LTS):

```
$ imagemin --help
/home/xxx/.nvm/versions/node/v8.16.0/lib/node_modules/imagemin-cli/node_modules/get-stdin/index.js:13
	for await (const chunk of stdin) {
	    ^^^^^

SyntaxError: Unexpected reserved word
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/xxx/.nvm/versions/node/v8.16.0/lib/node_modules/imagemin-cli/cli.js:5:18)
```

node 9:

```
$ imagemin
/home/xxx/.nvm/versions/node/v9.11.2/lib/node_modules/imagemin-cli/node_modules/get-stdin/index.js:13
	for await (const chunk of stdin) {
	    ^^^^^

SyntaxError: Unexpected reserved word
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at Object.runInThisContext (vm.js:197:10)
    at Module._compile (internal/modules/cjs/loader.js:618:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
```

node 10 (default in apt repository for Debian 10) does not support nvm.

nvm:

```
$ nvm --version
0.35.3
```

**Comment by webketje** [comment]
The [package.json file](https://github.com/imagemin/imagemin/blob/main/package.json#L9) states that Node.js < 12 is not supported. What version of Node is bundled by default by a Linux distro is not imagemin's responsibility.
