### ISSUE TITLE
not working on Windows 10, an error occurs

### ISSUE THREAD

**Issue by Lovor01** [imagemin/imagemin#387]
After setting all the paths to support glob syntax (forward slashes), I am still getting an error:
```
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

TypeError: Cannot destructure property 'ext' of '(intermediate value)' as it is undefined.
    at handleFile (file:///C:/Wamp.NET/sites/etnografski/wp-content/themes/web-muzeja/node_modules/imagemin/index.js:22:9)
    at async file:///C:/Wamp.NET/sites/etnografski/wp-content/themes/web-muzeja/node_modules/imagemin/index.js:54:13
    at async Promise.all (index 71)
    at async file:///C:/Wamp.NET/sites/etnografski/wp-content/themes/web-muzeja/optimizeimages.mjs:7:15
The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command npm run optimizeImages" terminated with exit code: 1.
```

**Comment by aleksanderwalczuk** [comment]
@Lovor01 you might consider using docker. I've got various errors trying to run a project using imagemin on mac OS 10.15, but it works well on linux using a docker container. Hope it helps

**Comment by sindresorhus** [comment]
Fixed by https://github.com/imagemin/imagemin/commit/a88735fce64dbd39c5872d30c42897846f5fb0ad.
