### ISSUE TITLE
After updating imagemin-cli from 6.0.0 to 7.0.0 a TypeError occurs

### ISSUE THREAD

**Issue by ahayzen** [imagemin/imagemin#389]
After updating the `imagemin-cli` package in npm from 6.0.0 to 7.0.0, the following error occurs while running the following command `imagemin src/static/**/*.svg --out-dir=build/minify/static`.

```
TypeError: Cannot destructure property 'ext' of '(intermediate value)' as it is undefined.
    at handleFile (file:///workspaces/electron-template/node_modules/imagemin/index.js:22:9)
    at async file:///workspaces/electron-template/node_modules/imagemin/index.js:54:13
    at async Promise.all (index 0)
    at async run (file:///workspaces/electron-template/node_modules/imagemin-cli/cli.js:100:11)
    at async file:///workspaces/electron-template/node_modules/imagemin-cli/cli.js:131:2
```

I am using node version `v16.4.1`.

**Comment by Uter1007** [comment]
same problem here

**Comment by antongolub** [comment]
`imagemin` was bumped to v8.0

[reasonable changes](https://github.com/imagemin/imagemin/compare/v7.0.1...v8.0.0#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346L23):
```js
let destinationPath = destination ? path.join(destination, path.basename(sourcePath)) : undefined;
destinationPath = (fileType(data) && fileType(data).ext === 'webp') ? replaceExt(destinationPath, '.webp') : destinationPath;
```
```js
const {ext} = await FileType.fromBuffer(data);
let destinationPath = destination ? path.join(destination, path.basename(sourcePath)) : undefined;
destinationPath = ext === 'webp' ? replaceExt(destinationPath, '.webp') : destinationPath;
```
`FT.fileType` was replaced with `FT.fromBuffer` 

...and as I can see `file-type/core.js`  has no detection for `svo`.

**Comment by bladeoflight16** [comment]
Also seeing the same issue.
