### ISSUE TITLE
Command failed

### ISSUE THREAD

**Issue by binarykitchen** [imagemin/imagemin#42]
I am getting this weird error on my Mac:

```
[14:59:33] Starting 'imagemin'...
{ [Error: Command failed: ]
  plugin: 'gulp-imagemin:',
  showStack: false,
  name: 'Error',
  message: 'Command failed: ',
  stack: 'Error: Command failed: \n    at ChildProcess.exithandler (child_process.js:647:15)\n    at ChildProcess.emit (events.js:98:17)\n    at maybeClose (child_process.js:755:16)\n    at Socket.<anonymous> (child_process.js:968:11)\n    at Socket.emit (events.js:95:17)\n    at Pipe.close (net.js:465:12)' }
```

the gulp code is:

``` javascript
gulp.task('imagemin', ['clean:img'], function() {
    return gulp.src(paths.uncompressedImages)
        .pipe(imagemin({
            optimizationLevel: 4,
            progressive:       true,
            interlaced:        true
        }))
        .on('error', console.error)
        .pipe(gulp.dest(paths.img))
})
```

**Comment by Xychun** [comment]
how?

**Comment by binarykitchen** [comment]
how can i remember? this ticket is so old ...
