### ISSUE TITLE
"Cannot read property 'contents' of undefined" - after npm & imagemin update

### ISSUE THREAD

**Issue by mobidev111** [imagemin/imagemin#73]
npm version 2.1.7

package.json

```
    "devDependencies": {
        "gulp-imagemin": "^1.0.1",
        "imagemin-pngcrush": "^1.0.0",
        ...
    },
```

After a fresh npm install the following error appears. This as well happens with "gulp-imagemin": "^1.2.1".
The same code worked with an earlier npm version.

```
/Users/Test/testproject/node_modules/imagemin-pngcrush/index.js:18
        if (!isPng(file.contents)) {
                       ^
TypeError: Cannot read property 'contents' of undefined
    at /Users/Test/testproject/node_modules/imagemin-pngcrush/index.js:18:18
    at Imagemin.use (/Users/Test/testproject/node_modules/gulp-imagemin/node_modules/imagemin/index.js:64:51)
    at Array.forEach (native)
    at DestroyableTransform.through.obj.percent (/Users/Test/testproject/node_modules/gulp-imagemin/index.js:47:16)
    at DestroyableTransform._transform (/Users/Test/testproject/node_modules/gulp-imagemin/node_modules/through2-concurrent/through2-concurrent.js:29:15)
    at DestroyableTransform.Transform._read (/Users/Test/testproject/node_modules/gulp-imagemin/node_modules/through2-concurrent/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/Test/testproject/node_modules/gulp-imagemin/node_modules/through2-concurrent/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/Test/testproject/node_modules/gulp-imagemin/node_modules/through2-concurrent/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Users/Test/testproject/node_modules/gulp-imagemin/node_modules/through2-concurrent/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/Users/Test/testproject/node_modules/gulp-imagemin/node_modules/through2-concurrent/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
```

**Comment by drewnoakes** [comment]
I'm seeing this issue pop up on OSX for a gulpfile that works on Linux. There's no difference to the contents of the pipe in either case.

**Comment by drewnoakes** [comment]
See also https://github.com/gruntjs/grunt-contrib-imagemin/issues/208.

**Comment by blindlybright** [comment]
I found a difference between previous gulp task on image optimization. Now it's useful to use imagemin-pngquant plugin instead of imagemin-pngcrush (as it shown on https://www.npmjs.com/package/gulp-imagemin)

**Comment by raydelto** [comment]
update the packages.json file and modify  your grunt-contrib-imagemin to   "grunt-contrib-imagemin": "^1.0.0",

**Comment by Dr-Sun** [comment]
I solve this question is like this
return gulp.src('src/images/*')   ----->  gulp.src('[src/images/*]')  
please see [https://github.com/gruntjs/grunt-contrib-imagemin/issues/208](url)
@stedda 
In task-runner on src u don't need the {} anymore.
Please replace the src like this : src: '[*/*.{png,jpg,jpeg,gif,svg}]', and put the path and specific images. 
For me that worked.
