### ISSUE TITLE
I can't use pngquant

### ISSUE THREAD

**Issue by hemedani** [imagemin/imagemin#80]
I'm set variable like this :
<pre>
<em>
var gulp = require('gulp'),
	gutil = require('gulp-util'),
	coffee = require('gulp-coffee'),
	compass = require('gulp-compass'),
	connect = require('gulp-connect'),
	minifyCSS = require('gulp-minify-css'),
	gulpif = require('gulp-if'),
	uglify = require('gulp-uglify'),
	minifyHTML = require('gulp-minify-html'),
	imagemin = require('gulp-imagemin'),
	pngquant = require('imagemin-pngquant'),
	concat = require('gulp-concat');
</em>
</pre>

and set the task like this :
<pre>
<em>
gulp.task('image', function() {
    gulp.src('bulid/dev/pic/**/*.*')
	.pipe(gulpif(env === 'dev', imagemin({
		progressive: true,
		svgoPlugins: [{ removeViewBox: false}],
		use: [pngquant()]
	})))
	.pipe(gulpif(env === 'dev', gulp.dest(output + 'tasavir/')))
	.pipe(connect.reload());
});
</em>
</pre>

but when i run gulp command in terminal throw this error ::(even if i run the <em>NODE_ENV=dev gulp</em>
<pre>
<em>
Error: Cannot find module 'imagemin-pngquant'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:280:25)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/amir/Desktop/aminisite/gulpfile.js:11:13)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
  at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:159:12)
  at module.exports (/usr/local/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
  at Liftoff.launch (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:152:5)
  at Object.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:67:5)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:929:3
</em>
</pre>

**Comment by kevva** [comment]
`npm install imagemin-pngquant`
