### ISSUE TITLE
this png file failed

### ISSUE THREAD

**Issue by ustccjw** [imagemin/imagemin#82]
![bank](https://cloud.githubusercontent.com/assets/4114358/5659800/43689ac0-9753-11e4-9114-d01a4e224e9f.png)

**Comment by sindresorhus** [comment]
What was the error message? Can you share the terminal output?

**Comment by ustccjw** [comment]
````
{ [Error: Command failed: /Users/ustccjw/work/git/ustccjw/haojing/tool/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor/optipng -strip all -quiet -clobber -o 1 -out /var/folders/v_/1_b3q2vx4z72755pp4kq6m040000gp/T/60ae32e0-1e9b-42c5-8295-0727c21b8bb1 /var/folders/v_/1_b3q2vx4z72755pp4kq6m040000gp/T/55b15346-7fe8-4cf7-ac7e-8339346543ce
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/Users/ustccjw/work/git/ustccjw/haojing/tool/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor/optipng -strip all -quiet -clobber -o 1 -out /var/folders/v_/1_b3q2vx4z72755pp4kq6m040000gp/T/60ae32e0-1e9b-42c5-8295-0727c21b8bb1 /var/folders/v_/1_b3q2vx4z72755pp4kq6m040000gp/T/55b15346-7fe8-4cf7-ac7e-8339346543ce',
  name: 'Error',
  message: 'Command failed: /Users/ustccjw/work/git/ustccjw/haojing/tool/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor/optipng -strip all -quiet -clobber -o 1 -out /var/folders/v_/1_b3q2vx4z72755pp4kq6m040000gp/T/60ae32e0-1e9b-42c5-8295-0727c21b8bb1 /var/folders/v_/1_b3q2vx4z72755pp4kq6m040000gp/T/55b15346-7fe8-4cf7-ac7e-8339346543ce\n',
  stack: 'Error: Command failed: /Users/ustccjw/work/git/ustccjw/haojing/tool/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor/optipng -strip all -quiet -clobber -o 1 -out /var/folders/v_/1_b3q2vx4z72755pp4kq6m040000gp/T/60ae32e0-1e9b-42c5-8295-0727c21b8bb1 /var/folders/v_/1_b3q2vx4z72755pp4kq6m040000gp/T/55b15346-7fe8-4cf7-ac7e-8339346543ce\n\n    at ChildProcess.exithandler (child_process.js:732:12)\n    at ChildProcess.emit (events.js:110:17)\n    at maybeClose (child_process.js:1000:16)\n    at Socket.<anonymous> (child_process.js:1168:11)\n    at Socket.emit (events.js:107:17)\n    at Pipe.close (net.js:461:12)',
  fileName: '/Users/ustccjw/work/git/ustccjw/haojing/htdocs/static/img/style/bank.png',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-imagemin:' }

````

**Comment by kevva** [comment]
It's working fine for me. What version of gulp-imagemin are you using?

**Comment by kevva** [comment]
@ustccjw ping.

**Comment by shinnn** [comment]
I reproduced the error and found the cause.

```
** Processing: /var/folders/2n/y4hbl_pd05l41w9rh15mm4700000gn/T/010b96a8-cf79-4b72-a00e-5b19f3228f54
Warning: Extraneous data found after IEND
288x110 pixels, 8 bits/pixel, 256 colors (256 transparent) in palette
Recoverable errors found in input. Rerun OptiPNG with -fix enabled.
Error: Previous error(s) not fixed

** Status report
1 file(s) have been processed.
1 error(s) have been encountered.
```

Adding `-fix` flag to `optipng` command will fix this. I'll update imagemin-optipng.

**Comment by shinnn** [comment]
Fixed. https://github.com/imagemin/imagemin-optipng/commit/1b2c2a54d51098501a5b581a2df4191d12dce15a

@kevva @sindresorhus Could you release a new version of imagemin-optipng, or add me as a npm owner?

**Comment by kevva** [comment]
@shinnn, added you.

**Comment by shinnn** [comment]
Done. https://github.com/imagemin/imagemin-optipng/commit/6aeb88857b203363ac431543beb06383c5f6346d

@ustccjw Reinstall gulp-imagemin.
